### ISSUE TITLE
[studio] Editorial BP targeting no longer works

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1039]
Targeting in Editorial BP no longer works.

Steps to Reproduce
---------------------------

- Create a site based on Editorial BP
- Switch targeting to guy and apply
- Note that changes didn't take

Ping me if you need anything.

**Comment by jdrossl** [comment]
@sumerjabri the current code is validating the `username` property and ignoring the profile if the value is `anonymous`, it looks like the new UI has removed the property and the value never changes.

**Comment by jdrossl** [comment]
@sumerjabri there is a validation around the `username` property, if it is set to `anonymous` then the profile is ignored, should I remove the validation and all code related to the property?

Also I think we are missing an option to clear the profile, because if you select `anonymous` for the segment the query looks for that value and the result is 0 articles.

**Comment by sumerjabri** [comment]
@jdrossl here is the ticket to clear: https://github.com/craftercms/craftercms/issues/1043

With regard to validation, that has been removed per https://github.com/craftercms/craftercms/issues/1035

With regard to anonymous being essentially an empty, the Editorial BP needs to treat equally:
* No profile
* No segment
* Segment is empty
* Segment is not "guy" nor "gal" (any other string)

In all of the above, the BP should treat as anonymous and not target.

**Comment by jdrossl** [comment]
@sumerjabri when you say that `Segment is not "guy" nor "gal" (any other string)` do you mean we need to validate it against the taxonomy used? because otherwise if a new value is added it would require a change in the code to include it. I think it would be better to change `anonymous` for empty in the targeting config.

**Comment by sumerjabri** [comment]
@jdrossl if segment provided in profile doesn't match any segment provided in taxonomy then assume anonymous (i.e. unknown user).
