### ISSUE TITLE
[social] API requests fails to execute

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#1104]
Calling a `PUT /api/3/comments/:id/attachments/:attachmentId` results in the following error:

https://gist.github.com/jdrossl/9ec0324e0507bfb1f1df44665ea3be3b

**Comment by cortiz** [comment]
Removed the `update attachment` to be a put since Tomcat will need a context param to allow multipart attachment to be read if is an HTTP PUT verb, since there is already an HTTP POST and PUT is not that often used. the PUT was removed.
Use `POST /api/3/comments/:id/attachments/:attachmentId/update`

**Comment by jdrossl** [comment]
Verified
