### ISSUE TITLE
[craftercms] Test backup and restore

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1134]
Please test backup and restore. You'll be able to backup/restore Crafter Studio using `crafter.sh` in the authoring environment.

**Comment by gortizcrafter** [comment]
Waiting for new MariaDB4j release to start the tests properly

reference : https://github.com/craftercms/craftercms/issues/685 ( Last coment of @jdrossl )

**Comment by sumerjabri** [comment]
@gortizcrafter test with what we have first and then we regression test when the MariaDB4J comes out

**Comment by luishernandezmonge** [comment]
Tested the Backup&Restore process on mac with next steps:

1. On your local crafter studio create a new site with Website_editorial BP
2. Executing the **./crafter.sh backup test21-08-2017** [with authoring-environment Up]
3. Stoping the authoring-env [**./gradlew stop**]
4.  Deleting all content of the **crafter-auth-env/data** folder [this because the restore process is not completed totally because a missing library of **Gustavo's comment above**]
5. Executing the restore with: **./crafter.sh restore craftercms/crafter-auth-env/test21-08-2017.2017-08-21-07-32-12.zip**
6. [Verification] go to **craftercms/crafter-auth-env/data** and review that all the data was restored successfully 
7. [Verification] go to folder mentioned above and validate if there are present the next items:
a) **yoursite-preview.yaml** on **data/deployer/targets/** folder
b) **yoursite** on **data/repos/sites/** folder
c) **admin** profile on **data/mongodb** folder

https://github.com/craftercms/craftercms/issues/685#issuecomment-315533180 note: this is the related ticket for missing library ** MariaDB4j**

-Couple of observations here:
1. [Improvement] When you execute the **./crafter.sh backup backupfilename**... maybe this can be placed on a directory like **backups** (this to get more clean environment folder)
2. [Possible issue] When you execute the restore process **./crafter.sh restore craftercms/crafter-auth-env/test21-08-2017.2017-08-21-07-32-12.zip** without shutdown the environment, the process returns some [Errors] but at sometime it returns a success message for restore (See the error-trace file) and after success it continues wait for the unlock of the database table (undefined time)
[Crafter-Restore_Error-Trace.txt](https://github.com/craftercms/craftercms/files/1239186/Crafter-Restore_Error-Trace.txt)

3. [Not Issue - Related to missing Library] the backed-up sites are not displayed on crafter studio after restores process

**Comment by sumerjabri** [comment]
File tickets for the issues and let's prioritize. I think some can be addressed with some documentation too.

**Comment by luishernandezmonge** [comment]
Tested all the backup/restore process and it is working OK.
Currently, all the sites are backed up and the user can access the site through the crafter studio
