### ISSUE TITLE
[studio] Bulk upload only uploads 1 asset when multiple assets have the same name 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1140]
when you upload folders A and B with the same files inside A and B folders ONLY A or B will contain the files.

https://www.useloom.com/share/424aebde5f894e2cb853dd0b5821baf6

**Comment by dejan-brkic** [comment]
This is UI issue. Per video, bulk upload dialog really sends only 4 write content requests to backend (4 files that were uploaded). There are also create folder requests for all empty folders.
Most probably bulk upload does not make difference between different sources with same file name.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio2-ui/pull/525

**Comment by russdanner** [comment]
This does appear to be fixed.

**Comment by russdanner** [comment]
https://www.useloom.com/share/0cf4cd6acdaa4e688761951300e28fdd

**Comment by jvega-crafter** [comment]
@russdanner this seems to be another issue, the files are being uploaded (you can check them on the repo folder), but the problem is that some filenames are not rendered on the tree ("index.xml", "crafter-component.xml" and "crafter-level-descriptor.level.xml"). The last one is rendered as "Section Defaults"

**Comment by russdanner** [comment]
This ticket can be closed.
