### ISSUE TITLE
[studio-ui] Jump to dropdown contains empty values

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1142]
<img width="1277" alt="screen shot 2017-07-21 at 3 32 52 pm" src="https://user-images.githubusercontent.com/169432/28479373-207bf5ba-6e2a-11e7-8c84-94a8e5f117d5.png">

You can look at health page in editorial blueprint to see example of issue

**Comment by vestrada** [comment]
Hi,

@alhambrav The problem is that the template doesn't contain iceGroup="" or label="" property.
Example:
<header id="header" <@studio.componentAttr path=contentModel.storeUrl ice=true />>
Should be:
<header id="header" <@studio.componentAttr path=contentModel.storeUrl ice=true iceGroup="header" />>

Thanks :)

**Comment by alhambrav** [comment]
Done.
PR https://github.com/craftercms/studio/pull/804

**Comment by russdanner** [comment]
Verified
