### ISSUE TITLE
[studio] Bulk go-live causes repeat publishing of item which breaks publisher

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1174]
Steps to Reproduce
===============
* Create a site based on Editorial BP
* Create a page `Test Page`
* Create a child page `Test Child Page`
* Publish child page
* Invoke bulk publish

The system tries to republish `Test Child Page` and it breaks.

**Comment by dejan-brkic** [comment]
Can not reproduce anymore
Fixed as side-efect of dependencies issue (https://github.com/craftercms/craftercms/issues/1171) or steps are incorrect.

**Comment by russdanner** [comment]
@dejan-brkic 
Create a site based on Editorial BP
Create a page Test Page
Create a child page Test Child Page
Publish child page
Invoke bulk publish for /site/website 
Parent gets published but Test Child Page does not

**Comment by dejan-brkic** [comment]
invalid use case

With dependency fix (#1171), when child page published manually, parent gets published too. Both pages need to be edited again and child page published again, so that parent does not get pulled by dependency calculator. So when bulk go live is executed parent gets published and child not (it is fine because it is already live). and publisher does not get broken as it is stated in the ticket

**Comment by russdanner** [comment]
Bulk publish should publish everything that is still unpublished below the specified path
I simplified the use case

- Create page under home called a with child b and child c (of b)
- bulk publish
- a is published but b and c are not

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/825

**Comment by russdanner** [comment]
Verified
