### ISSUE TITLE
[studio] Add content type controllers to dependencies

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1408]
Content type controllers are not listed in dependencies

1. Using website_editorial, open the **Sidebar**
2. Preview any of the pages.  For the example below, preview the category landing page, **Entertainment**

<img width="1435" alt="screen shot 2017-10-02 at 10 37 07 am" src="https://user-images.githubusercontent.com/25483966/31082858-020fa456-a75e-11e7-9902-6affcb11a1a5.png">

3. Click on **Dependencies** from the context nav.  Notice that the script **category-landing.groovy** is not listed in the dependencies.

<img width="1294" alt="screen shot 2017-10-02 at 10 40 43 am" src="https://user-images.githubusercontent.com/25483966/31082928-3071d4fe-a75e-11e7-9a61-daaf2ccf37ca.png">

<img width="1293" alt="screen shot 2017-10-02 at 10 42 20 am" src="https://user-images.githubusercontent.com/25483966/31083000-6286c0a8-a75e-11e7-83b4-92ac8e898e01.png">

Here's another example, preview the **Home** page, then click on **Dependencies**
<img width="1435" alt="screen shot 2017-10-02 at 11 00 26 am" src="https://user-images.githubusercontent.com/25483966/31083933-0aae871e-a761-11e7-903c-37b4fe309342.png">

Notice that the script **home.groovy** is not listed in the dependencies of the **Home** page
<img width="1295" alt="screen shot 2017-10-02 at 11 02 17 am" src="https://user-images.githubusercontent.com/25483966/31083974-2a6f1762-a761-11e7-8dfb-19911c913e91.png">

<img width="1294" alt="screen shot 2017-10-02 at 11 02 33 am" src="https://user-images.githubusercontent.com/25483966/31083991-3626c1c2-a761-11e7-99b2-e4592fbf03f4.png">

**Comment by dejan-brkic** [comment]
Content Type controllers are not explicitly referenced in any content. Dependency extraction is based on regular expression recognition from explicit content. Therefore dependency extraction fails to recognize groovy script as dependencies.
We need to add new feature for this kind of dependency extraction. Besides new feature, naming convention needs to be aligned because content type names and script location do not match (without transformation).
@sumerjabri we need to discuss how to tackle this issue. Potential problem is that content type controller is actually engine feature and configured separately from studio.

**Comment by sumerjabri** [comment]
@dejan-brkic let's just make it such that, page/component dep calc uses the convention spec'd in engine for dep calc for controllers associated (yes, both pages and components have that).

We no longer need additional filters/drop down.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/961

Issue is fixed by adding configuration for dependency resolver

**Comment by alhambrav** [comment]
Verified fixed.
