### ISSUE TITLE
[docs] Document missing APIs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#1701]
Per our conversation, please document Write Content API and see if we're missing any other APIs.

**Comment by rart** [comment]
Regarding write content, through studio UI's code, I noticed the UI sends: user, phase, site, path, fileName, unlock... and `nocache`.

- Please specify the possible values of `phase` and the meaning of each.
- Is it possible for the backend to take the user it from the active session? What's the purpose of sending the user? Can admins write impersonating someone else?
- Is this the same call for uploading a file versus updating a file (e.g. changing a ftl template). If not, could it work just with the asset id rather than specifying path & file name?

**Comment by dejan-brkic** [comment]
PR: https://github.com/craftercms/docs/pull/423

There are  still some more undocumented APIs (i have full list). Those APIs are either obsolete, or not referenced in UI, or recently added by other developers without being documented.

@sumerjabri  I think we need to discuss how to handle those APIs and its docs.

**Comment by sumerjabri** [comment]
Batched for documentation/deletion as appropriate.
