### ISSUE TITLE
[studio] 2.5.x delete action leaves empty page-specific folder when deleting a page 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1813]
### Expected behavior
If you delete a page with page specific items and the folder is empty, the folder should be deleted.
The easy answer would be to delete the folder no matter what but this will negatively impact anyone who has /site/components and /static-assets/ set as page specific so it's not an option

### Actual behavior
https://www.useloom.com/share/8c910771356f4fd39994525c5e9ab497

### Steps to reproduce the problem
* create an item with page specific image assets
* delete the page
* note that the folder in static assets is left

**Comment by dejan-brkic** [comment]
The second part of expected behavior makes complicated implementation. The recommended workaround is using delete dependency configuration on content types. This configuration has remove empty folder option:

```
<delete-dependencies> 
    <delete-dependency> 
        <pattern>(^/static-assets/dd/.*)</pattern> 
        <remove-empty-folder>false</remove-empty-folder> 
    </delete-dependency> 
</delete-dependencies> 
```
Otherwise we need to design more sofisticated algorithm to delete folder but not self-destroy repository structure

**Comment by russdanner** [comment]
CONFIRMED
