### ISSUE TITLE
[studio-ui] Box controller should not deleted selected files

### ISSUE THREAD

**Issue by cortiz** [craftercms/craftercms#1926]
### Expected behavior
Box controller should not delete selected and store files and also should allow to manually delete the files
### Actual behavior
If nothing is chosen selector deletes existing options and users have to redo the choosing of files.
### Steps to reproduce the problem
*  Create or use an existing content-type with and create a content.
*  Edit the content and do not choose any files
* Reopen the content just edited and there original selection is gone.

#### Version
Any
#### OS
Any
#### Browser
Any

**Comment by vestrada** [comment]
Per our conversation, The issue is working on the lasted studio version:
Studio Version Number: 3.0.10-SNAPSHOT-a7e860
Build Number: a7e860de3bee814293d02941bc632a5a4b678f25
Build Date/Time: 03-07-2018 10:44:40 -0600
Please see the following video:

https://www.useloom.com/share/0299756a7ec24e8dae7222e04e31404e

I will work on the enhancement about adding a way the user can manually delete the files.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/787
