### ISSUE TITLE
[studio-ui] Save as draft on new item puts item at wrong path

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1977]
### Expected behavior
Item should be created at the path expected/chosen by the user

### Actual behavior
Pages are created outside of /site/website

### Steps to reproduce the problem
* Right-click on the home page in the sidebar under pages
* Click create new, chose a type
* Enter some content
* Save as draft
* Note content is not created in the proper location

**Comment by dejan-brkic** [comment]
UI issue. The backend is saving content according to service parameters being sent.
The issue is not described properly. The draft is undocumented, so there is no defined location where draft content is expected to be saved. The last step in the description does not have much sense since the proper location is unknown (undocumented) and not specified in the steps

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/805

**Comment by sumerjabri** [comment]
Verified.
