### ISSUE TITLE
[studio-ui] dashboard columns styles should be consistent

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2270]
### Expected behavior
Dashboard columns styles should be consistent
* All sortable columns should be the same color blue.  
* All sortable columns should have a desc/asc indicator 
* Any column heading that wraps should center

### Actual behavior
<img width="1035" alt="screen shot 2018-07-06 at 1 08 06 pm" src="https://user-images.githubusercontent.com/169432/42391659-1e8f2422-811e-11e8-9f8b-c8d9f19e46e5.png">

### Steps to reproduce the problem
N/A

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Studio Version Number: 3.0.15-SNAPSHOT-ff6bde
Build Number: ff6bde003de5b8440809d2f75e5e9db2c473b7a9
Build Date/Time: 07-06-2018 12:53:20 -0400

#### OS
All
#### Browser
All

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/876

Russ per our conversation:
- All sortable columns should be the same color blue. -> Fixed
- All sortable columns should have a desc/asc indicator -> This won't be fixed, because the indicator shows the current sort.
- Any column heading that wraps should center -> I have made all the labels consistent. I made it all `Publish Date`. 

Thanks

**Comment by russdanner** [comment]
Confirmed
