### ISSUE TITLE
[studio] edit pencils do not track markup during a scroll when absolute positioning is used

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2456]
### Expected behavior
Pencils should remain with the element (on and off screen) during scrolling

### Actual behavior
Specific CSS configurations do not interplay with the pencil configutration 
```    
position: absolute;
top: 0;

```

### Steps to reproduce the problem
* Create a site based on editorial 
* Turn pencils on
* Scroll the window.  Note the pencil on the header does not stick with the header

### Log/stack trace (use https://gist.github.com)
N/A

#### Version
Any

#### OS
Any

#### Browser
Any

**Comment by ducqui** [comment]
Note. If the body has the scrollbar, then the pencils will appear to "move with the parent elements".
The issue is only duplicated when a parent element (div) has a different position and is not relative to body (ie position: fixed or absolute).

Also, the pencils do not interact with AJAX or other JS. If you have a slideshow of divs, then all of the pencils would be on top of each other. Furthermore, the pencils do not appear if the elements are created with AJAX. They only appear if it's part of the DOM at the time you click the in-context editing. Improvement can be to respond to the generic data-ice attributes so that JS-triggered events can interact with the pencils.

**Comment by vestrada** [comment]
PR: https://github.com/craftercms/studio-ui/pull/944

The Name of the repaint functions is: `studioICERepaint()`

**Comment by vestrada** [comment]
PR: 3.0.x: https://github.com/craftercms/studio-ui/pull/945

**Comment by russdanner** [comment]
Confirmed
