### ISSUE TITLE
[studio] publisher stops when metadata is not found for object

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2472]
### Expected behavior
Publisher should not stop if metadata is not available.
Or it should not be possible to get in to a state where metadata is not available.

### Actual behavior
Publisher stops due to an exception.  See stack trace

### Steps to reproduce the problem
This situation was created with a merge conflict during a code forward operation.  The steps below simplify the process so that it can be easily replicated locally.
*  create a clone of sandbox 
* in the clone, create a content type, add and commit it.  delete the content type. add and commit the delete. change the /site/website/index.xml.  add and commit that change. 
* In the sandbox: change the /site/website/index.xml.  add and commit that change. 
* in the clone, pull. this will result in a conflict. fix the and commit. pull. and push the commit to sandbox.
* In the sandbox acquire the latest commit id from the git log.  
* immediately publish the commit ID via studio
* the publisher will stop on the removed content type that was never in sandbox.

Note:  It's not possible to replicate the error without including an edit of an existing file as part of the push.  

### Log/stack trace (use https://gist.github.com)
https://gist.github.com/russdanner/8087c563de02bee886513ed98086c58d

#### Version
```Studio Version Number: 3.0.17-SNAPSHOT-6a16db
Build Number: 6a16dbcfe2f541b8461685982797a321d2d3ae6f
Build Date/Time: 09-10-2018 22:28:01 -0400
```
#### OS
All

#### Browser
All

**Comment by sumerjabri** [comment]
@russdanner What version is this? `3.0.16`?

**Comment by jdrossl** [comment]
@sumerjabri @dejan-brkic this seems to be the intended behavior (disable publishing for the site so the issue can be reviewed and then start it manually from the ui)? So let me know if that should be changed or not.

However, I think there is a bug in the git log processing because the history seems to ignore all commits pushed from the cloned repo.

<img width="455" alt="screen shot 2018-09-14 at 8 49 34 am" src="https://user-images.githubusercontent.com/1236955/45559117-d94bcd80-b7fe-11e8-91e0-b043e7fb14fd.png">

![screen shot 2018-09-14 at 8 49 56 am](https://user-images.githubusercontent.com/1236955/45559122-dbae2780-b7fe-11e8-9516-44e96fd9be4f.png)


@russdanner did you try this in 3.0.x or 3.1.x? in 3.1.x I was able to replicate only publishing the commit where the content-type is added, not with the latest commit, also did you try to use this API https://docs.craftercms.org/en/3.0/developers/projects/studio/api/repo/sync-from-repo.html? according to the doc it is required when the repo changes manually.

**Comment by russdanner** [comment]
This is replicable on both 3.0.16 and 3.0.17 builds.

**Comment by russdanner** [comment]
```
[ERROR] 2018-09-13 21:20:34,230 [studioSchedulerFactoryBean_Worker-6] [job.DeployContentToEnvironmentStore] | Error while executing deployment to environment store for site "test", number of items "10"
org.craftercms.studio.api.v1.service.deployment.DeploymentException: No metadata found for test:/config/studio/content-types/page/new/config.xml
	at org.craftercms.studio.impl.v1.service.deployment.PublishingManagerImpl.processItem(PublishingManagerImpl.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)```

Or specifically this error blocks the deployment:  ```org.craftercms.studio.api.v1.service.deployment.DeploymentException: No metadata found for test:/config/studio/content-types/page/new/config.xml```  

Even creating a content type in authoring sandbox did not seem to address the issue.

My question here is, is missing metadata on an item that doesn't exist a reason to have an exception and block all deployments?

**Comment by russdanner** [comment]
https://www.useloom.com/share/1f1d2601e2374e7187f27e6211986377

No branch or clone is needed to replicate the error
The issue occurs even if sync runs

Simple steps
In sandbox: 
- add an object, git add and commit to index 
- remove the object, git add and commit to index

Example using editorial blueprint:
`
cp -rp site/website/health site/website/healthc
git add --all .
git commit -m 'added'
rm -rf site/website/healthc
git add --all .
git commit -m 'removed'
git --no-pager log -n 2
`
- git log to get the commit ids
- publish the commit id for the add
- get the error from the publisher: No metadata found for editorial:/site/website/healthc/index.xml

**Comment by sumerjabri** [comment]
@dejan-brkic see the last comment on how to reproduce. Ping me to discuss once you have an understanding of what's going on.

**Comment by russdanner** [comment]
Confirmed
