### ISSUE TITLE
Form engine fails to load a form due to CmisObjectNotFoundException.

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#259]
The form load fails while it's trying to load form-controller.js. The followng error log captured in Studio: 
`[ERROR] 2016-11-04 12:07:11,736 [ajp-bio-7009-exec-5] [alfresco.AlfrescoContentRepository] | Error getting content from CMIS repository for path:
org.apache.chemistry.opencmis.commons.exceptions.CmisObjectNotFoundException: Object not found: /cstudio/config/sites/acme/content-types/page/article/form-controller.js?version=1fbbe9d83baaa26cd41638fe20c3d46368ff9269
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.convertStatusCode(AbstractAtomPubService.java:484)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.read(AbstractAtomPubService.java:645)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.getObjectInternal(AbstractAtomPubService.java:868)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.ObjectServiceImpl.getObjectByPath(ObjectServiceImpl.java:634)
	at org.apache.chemistry.opencmis.client.runtime.SessionImpl.getObjectByPath(SessionImpl.java:556)
	at org.apache.chemistry.opencmis.client.runtime.SessionImpl.getObjectByPath(SessionImpl.java:534)
	at org.craftercms.studio.impl.v1.repository.alfresco.AlfrescoContentRepository.getContentStreamCMIS(AlfrescoContentRepository.java:575)
	at org.craftercms.studio.impl.v1.repository.alfresco.AlfrescoContentRepository.getContent(AlfrescoContentRepository.java:119)
....
Caused by: java.lang.NullPointerException
	at javax.activation.MimetypesFileTypeMap.getContentType(MimetypesFileTypeMap.java:299)
	at org.craftercms.studio.impl.v1.util.spring.mvc.BinaryView.renderMergedOutputModel(BinaryView.java:100)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:267)
...
`

form-controller.js in question only has 1 version in Alfresco
![screen shot 2016-11-04 at 1 17 10 pm](https://cloud.githubusercontent.com/assets/4325885/20015247/0d6cc46e-a291-11e6-9739-2430a50da36d.png)

and the service call is attaching version=1fbbe9d83baaa26cd41638fe20c3d46368ff9269 as a parameter. The service call works without the version param.

**Comment by dejan-brkic** [comment]
Issue can not be reproduced with latest code base for 2.5.x branch.
Stacktrace is referencing a path that does not exist in studio code base (default content types). We can only assume that this issue is implementation specific or content specific issue. Therefore it can not be reproduced without actual content and content types that are throwing error.

**Comment by hlim** [comment]
why is this ticket closed? "form-controller.js" file exists in the repo but it's throwing 500 error with version parameter attached to the service call. The service call works fine without version parameter.

**Comment by russdanner** [comment]
I am re-opening this issue to make sure we talk through everything

**Comment by russdanner** [comment]
This form controller is not the Server-side JS but something that runs on the client side?

On the server side we have groovy based controllers, not JS based controllers (Stating in 2.5.0)

**Comment by hlim** [comment]
this form-controller.js lives in the content type folder and gets loaded if exist and yes I believe this runs on the client side. This is not the same as controller.js which now changed to controller.groovy.

below is a sample content of form-controller.js
`CStudioForms.FormControllers.ArticleController = CStudioForms.FormControllers.ArticleController ||  function() {
};

YAHOO.extend(CStudioForms.FormControllers.ArticleController, CStudioForms.FormController, {
    isFieldRelevant: function(field) {
       // ....
        return true;
    }

});


CStudioAuthoring.Module.moduleLoaded("/page/article", CStudioForms.FormControllers.ArticleController );`

**Comment by hlim** [comment]
can you please set a priority to this item to critical? It's impacting testing since we are not able to open multiple forms.

**Comment by russdanner** [comment]
Yes. That code runs on the client side.  Interesting feature... I think that one was contributed without my involvement but I understand the need for it.

**Comment by dejan-brkic** [comment]
I will add same comment again since it seems nobody put any attention what it says:

Issue can not be reproduced with latest code base for 2.5.x branch.
Stacktrace is referencing a path that **does not exist in studio code base (default content types)**. We can only assume that this **issue is implementation specific or content specific issue**. **Therefore it can not be reproduced without actual content and content types** that are throwing error.

Additionally if the code in question runs on client side, than it seems like it is UI issue or the way it UI is loading the content.

**Comment by russdanner** [comment]
Dejan, I did read your comment but also spoke with Hyanghee. 

These are optional files that get added to a content type.  The problem is that the UI is not able to download these files for some reason.

Looking at the Hyanghee's comment: `version=1fbbe9d83baaa26cd41638fe20c3d46368ff9269` I have to ask... Why are we attaching a version.  So I'll leave this with me for the minute -- I can't imagine why we would be trying to pull a version of the file.

**Comment by russdanner** [comment]
Inbound URL is:
http://HOSTNAME/studio/api/1/services/api/1/content/get-content-at-path.bin?path=/cstudio/config/sites/SITEID/content-types//page/one-column-rn-wide/form-controller.js&version=9bd9df622436b82e5c039b4813603f82919d1fa5

&version creates the bug.

Jose,

The addJS functions are correctly assuming they can add a param to bust the cache.  In the case of a service call Starts with "/api/1/services/" dont add the cache buster.



                            CStudioAuthoring.Module.requireModule(
                                formId+"-controller",
                                "/api/1/services/api/1/content/get-content-at-path.bin" +
                                "?path=/cstudio/config/sites/"+CStudioAuthoringContext.site+"/content-types/"+formId+"/form-controller.js",
                                moduleConfig, moduleCb);
                        }```

**Comment by asotog** [comment]
will take a look at this as well

**Comment by asotog** [comment]
If you see the commit, issue was not the parameter, it was how the parameter was being added to the service URL, also added an utility method to add url parameters
