### ISSUE TITLE
Folders are displayed as components in the Image Browse

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#264]
1) Create or edit a content that has RTE configured with image browse
2) Insert an image by browsing

See the screenshot attached. The component icon is used to represent folders.

![screen shot 2016-11-04 at 5 54 48 pm](https://cloud.githubusercontent.com/assets/4325885/20023643/d1d8e442-a2b7-11e6-8009-643795b8df6b.png)

**Comment by asotog** [comment]
will take a look at this

**Comment by asotog** [comment]
This seems weird to me @russdanner  if you see the item is saying a folder `isComponent: true` and `component: false`, that is why rendering icon as component instead of folder, this is coming from `http://localhost:8080/studio/api/1/services/api/1/content/get-items-tree.json?site=tests&path=/static-assets/images&depth=1&order=default&nocache=Tue%20Nov%2022%202016%2009:52:03%20GMT-0600%20(CST)&nocache=Tue%20Nov%2022%202016%2009:52:03%20GMT-0600%20(CST)`

<img width="423" alt="screen shot 2016-11-22 at 9 54 05 am" src="https://cloud.githubusercontent.com/assets/813023/20530820/3e059d6e-b09a-11e6-8e59-3c11f26bb02e.png">

**Comment by russdanner** [comment]
Note Jose is actually replacing browse feature.

**Comment by asotog** [comment]
great i can temporarily fix it from js to make look fine meanwhile new feature comes
