### ISSUE TITLE
[studio] Can't create site based on BP with the option to push to git repo (local bare)

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2744]
## Describe the bug
Error when creating a site based on a BP and linking to upstream git repo(local bare) 

## To Reproduce
1. Create a local bare git repo `git init –bare`
2. Go to studio an create a new site, select the option Link to upstream remote Git repository
3. Fill the fields, in remote branch paste your local bare git repo path `/Users/xxx/local_bare_repo` and auth type none
4. Select Create site based on a blueprint then push to remote bare Git repository

## Expected behavior
The site is created without errors

## Logs
https://gist.github.com/yacdaniel/448b34ffb7a132de1559e2eff8c822ae

### Version
Studio Version Number: 3.1.0-SNAPSHOT-959310
Build Number: 9593103c9431f4d734d7beb61c587357b37e11fb
Build Date/Time: 12-20-2018 07:54:49 -0600

### OS
Linux/Mac

### Browser
Chrome/Firefox

**Comment by dejan-brkic** [comment]
This is not the studio issue. It is related to security policies. I can reproduce this issue using directories on a random location on disk. However, if I create "remote" bare repository as a sibling to sites repositories, push works fine.

@sumerjabri @avasquez614 We need to discuss if this is a valid use case, and how to address security policies.

**Comment by avasquez614** [comment]
@sumerjabri @dejan-brkic. This issue occurs because Studio is trying to access somewhere outside of its permissions (`/Users/xxx/local_bare_repo`). So we have 2 options:

1. We turn off the Java policy by default, and recommend how to turn it on on prod environments and how to do it.
2. Java policy is turned on always, and we show developers/sysadmins how to add permissions for other locations outside of `bin`, `data` and `logs`.

**Comment by avasquez614** [comment]
@yacdaniel after some discussion, this shouldn't actually be an issue, because Git pushing to a folder outside of the Crafter install only seems to be something that is done during test cases. So whenever you need to do this test please do it under a `$CRAFTER_INSTALL/data/tests`.
