### ISSUE TITLE
[studio] Can't create site based on remote git repo using private key

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#2750]
## Describe the bug
Error when creating a site based on remote git repo using private key as authentication type 

## To Reproduce
1. Have a site published in a remote git repository
2. Go to Studio -> Sites and click Create Site
3. In the Create Site form check the `Link to upstream remote Git repository`
4. Fill the required fields, select auth type `Remote Git Repository Private Key` and  in Options check `Create site based in remote Git repository`
4. Click create and check catalina logs

## Expected behavior
The site is created without errors

## Logs
https://gist.github.com/yacdaniel/b3681784256056337ee3e548ba102545

### Version
Studio Version Number: 3.1.0-SNAPSHOT-eaa094
Build Number: eaa094e3adf8286bb8a4433dd2099d2393b18977
Build Date/Time: 12-26-2018 07:15:27 -0600

### OS
Linux & Mac

### Browser
Any

## Additional context
Using basic auth works and the site is created based on the git remote repo.

**Comment by christophercalm** [comment]
This issue is completely breaking our workflow as we cannot use shared keys.

**Comment by avasquez614** [comment]
@christophercalm what version of the software are you using? 3.0.x?

**Comment by christophercalm** [comment]
@avasquez614 Correct. 3.0.18

**Comment by avasquez614** [comment]
@christophercalm This might help:

1. Make sure what you're copying in the input box is the private key, and not the public key (e.g. `id_rsa` instead of `id_rsa.pub`).
2. Right now the only keys that work are RSA keys, so make sure that when you generate them with `ssh-keygen -b 4096 -t rsa` and that the file starts with the following header: `-----BEGIN RSA PRIVATE KEY-----`.

This might not be the cause of this particular issue, we're still determining it, but the stacktrace is similar to the ones we've got when using a non-RSA key.

**Comment by dejan-brkic** [comment]
Currently, we are supporting RSA keys. OpenSSH keys are not supported by the 3rd party library.
