### ISSUE TITLE
 Depth param is never used other than for logging

### ISSUE THREAD

**Issue by jvega-crafter** [craftercms/craftercms#286]
org.craftercms.studio.impl.v1.service.content.ContentServiceImpl#getContentItemTree(java.lang.String, java.lang.String, int)

Depth parameter is not working on services/api/1/get-pages

**Comment by cortiz** [comment]
@jvega-crafter  I did fix the issue on my 2.5.x branch http://github.com/cortiz/studio2 please triple check that all browse functionality  is working as it use to be since it it was defaulting to 2 regardless of the depth param , now it will actually honor the param so in some cases some trees will only have 1 child . When I have the Ok from you I'll merge the fix in 2.5.x and master
