### ISSUE TITLE
[studio-ui] Preview tools support in guest fails due to CORS issues when preview server is on different domain 

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2985]
## Describe the bug
Preview server / Studio communication fails to initiialize properly when the preview server is configured on a different domain than the authoring server.

## To Reproduce
1. Add a host entries from 127.0.0.1  (example: 127.0.0.1       localhost demo.com test.com)
2. Start/run a node based react, vue or other project running Node that has studio hints in it (usually port 3000) 
3. Load studio on http://demo.com:8080/studio
4. Create a project based on empty then go to config and set the preview server to http://test.com:3000
5. Go back to studio preview, you will see your application.  
6. Make sure your node/react app has the proper guest script code
```    <script src="http://demo.com:8080/studio/static-assets/libs/requirejs/require.js" data-main="http://demo.com:8080/studio/overlayhook?page=x&site=id&cs.js"></script>```
7. Note the errors in the javscript console
```overlayhook?page=x&site=id&cs.js:1 Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'demo.com' is not a suffix of 'localhost'.
    at http://demo.com:8080/studio/overlayhook?page=x&site=id&cs.js:1:17
```
## Expected behavior
Pencils and other preview features should work across domains

### Version
Software version if applicable (copy paste from Help > About).
3.x

### OS
All

### Browser
Any

## Additional context
I tried catching/ignoring the immediate error.  This leads to further CORS errors later in the script when the guest refers to `window.parent`

**Comment by rart** [comment]
The error occurs because overlayhook **always** sets the document domain of the host and it will always fail when the to origins aren’t of the same domain.

Recent code updates dismissed the use of `window.parent` which means that we might not need to set the document domain at all since the postMessage API doesn’t play by the same origin policies other browser APIs do.

All we can do is try/catch the document domain setting and handle it gracefully since, trying to set demo.com to test.com is simply not possible. **At this time** the setting of document.domain is probably of no use and can be removed. What can be done for this ticket is removing it (not commenting it!) and verifying it’s not missed.

**Comment by jvega190** [comment]
Tested removing the setting of document.domain, preview tools working on this scenario (different domains)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1099

**Comment by russdanner** [comment]
Confirmed
