### ISSUE TITLE
[studio-ui] Enhance TinyMCE5 support and usability

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#2988]
- Allow the form engine to control the tinyMCE configuration structure.
- Pull in the style sheets for the site and set the outer elements of the DOM so that the styles apply appropriately.
- Allow the form engine to set the width of the RTE
- The RTE should have an option that allows it to grow longer automatically as the author types more text.  The height defined in the RTE is the minimum height of the control.
- Do not allow the toolbar to scroll off the page.  Hook it to the top of the RTE, no matter how long the RTE editor.	
- Open image properties on double click. At the moment, they have to highlight the image then click insert. Doesn't make sense. 
- The code editor should take over the full screen

**Comment by jvega190** [comment]
Hi @russdanner, can you explain a little bit more this enhancements please?

- Allow the form engine to control the tinyMCE configuration structure.
- Pull in the style sheets for the site and set the outer elements of the DOM so that the styles apply appropriately. _(is this to get styles from site applied in here, removing selectors from site that are not into rte markup?)_
- Do not allow the toolbar to scroll off the page. Hook it to the top of the RTE, no matter how long the RTE editor.

thanks!

**Comment by russdanner** [comment]
These are done:
- Allow the form engine to control the TinyMCE configuration structure.
- Pull in the style sheets for the site and set the outer elements of the DOM so that the styles apply appropriately.
- Allow the form engine to set the width of the RTE

**Comment by russdanner** [comment]
I am moving these to 3.1.2
- The RTE should have an option that allows it to grow longer automatically as the author types more text. The height defined in the RTE is the minimum height of the control.

- Do not allow the toolbar to scroll off the page. Hook it to the top of the RTE, no matter how long the RTE editor.

- Open image properties on double click. At the moment, they have to highlight the image then click insert. Doesn't make sense.

- The code editor should take over the full screen

**Comment by russdanner** [comment]
This is an example of the scrolling issue:
https://www.loom.com/share/b9f4b160246c4482bc0bcf2d225820c9

**Comment by russdanner** [comment]
Confirmed
