### ISSUE TITLE
[docs] Update the status of 3.1.0 docs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3097]
Please update the pages indicating what's up to date with 3.1.0 and what's not.

**Comment by sumerjabri** [comment]
These files are not "Up to Date":
```
./source/developers/form-controls/list-form-controls.rst
./source/developers/form-sources/list-form-sources.rst
./source/release-notes/3-1-1.rst
./source/release-notes/3-1-3.rst
./source/release-notes/3-1-0.rst
./source/release-notes/3-1-2.rst
```
I used this script to find these:
```
for i in `cat t`; do grep "is-up-to-date" $i > /dev/null; if [[ $? != 0 ]]; then echo $i; fi; done
```

**Comment by alhambrav** [comment]
I did not put the up to date tags there, since it's an include, and if you add in the tag, it displays like this for the release notes:
![Screen Shot 2019-09-18 at 9 46 31 AM](https://user-images.githubusercontent.com/25483966/65154330-505f0780-d9f9-11e9-830d-7b5aa78cf775.png)

For the lists it displays like this:
![Screen Shot 2019-09-18 at 9 48 55 AM](https://user-images.githubusercontent.com/25483966/65154533-aa5fcd00-d9f9-11e9-9138-9b64d367d10d.png)
