### ISSUE TITLE
The gradle script still references .bat scripts

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3117]
## Describe the bug
Running `./gradlew start` in windows will try run `startup.bat`

## Expected behavior
Maybe it should display a message indicating that Windows is only supported via Docker

### Version
3.1.0

**Comment by avasquez614** [comment]
@jdrossl @sumerjabri we can show a message saying you need Docker when trying to run `gradlew start`. However, we shouldn't support ANY development task in Windows. The `craftercms` project shouldn't be used in Windows at all, because it will generate the files that are copied to Docker with the incorrect line endings and the wrong permissions. So a solution Sumer proposed is to remove the `gradlew.bat`. We should also say in the `README.md` of https://github.com/craftercms/craftercms that source code building is not supported in Windows and instead the Dockers should be used when running Crafter. Any comments on this?

**Comment by jdrossl** [comment]
That sounds good, we just need to make sure the doc is highly visible

**Comment by sumerjabri** [comment]
@avasquez614 let's do it.

**Comment by jdrossl** [comment]
Verified
