### ISSUE TITLE
[studio] Auto-build sass sheets within Studio for Studio (not sites)

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#3118]
**Is your feature request related to a problem? Please describe.**
Developers must manually build and push the build output of the sass sheets.

**Describe the solution you'd like**
The Studio internal build system should take care of this.

**Additional context**
To do this, the build system can do it in a few different ways. Best might be lib sass (see https://sass-lang.com/libsass). Other alternatives is using node via node-sass or the cli running:
```
sass --style=compressed --update ui/scss/temp.scss:static-assets/styles/temp.css ui/scss/user-dashboard/user-dashboard.scss:static-assets/styles/main.css
```

**Comment by jdrossl** [comment]
@rart as you mention there are a couple of options, basically we have to choose based on the plans for the future of the repo (adding react components for example)

- I tested a plugin that allows maven to use `libsass` but there are some limitations: it only receives a folder as input & output so some files would need to be renamed (from your example `user-dashboard.scss` vs `main.css`, probably there are more) and there are some errors showing up that seem to be typos easy to fix

- There is also the `node & npm/yarn` plugin that we have already used, it would allow you to fully control the configuration & add more tasks without having to change anything in maven, this could be helpful to integrate react components if those will be in the same repo

- Using `sass` directly is also possible but I would not recommend it because it will make the build process depend on a external binary and someone with a different version could break it (and also it's not too CI friendly)

Let me know which one do you think is better (by the way we could even use both maven plugins together if you want to keep sass & react completely independent from each other)

**Comment by rart** [comment]
Particularly because of the maven/libsass limitations sounds like yarn is the way to go.

I also like that option since we will need node processes for building future react artefacts.

**Comment by jdrossl** [comment]
@rart please add the `package.json` file in the ui repo, then I can setup maven to run the tasks defined there

**Comment by rart** [comment]
@jvega190 @vestrada please list all sass sheets that are maintained as sass and manually built every time modified (e.g. temp.scss, etc.)

For example, guest.scss doesn't seem to correspond to guest.css, correct?

Please describe.

@jdrossl feel free to modify the out dir or other params as it suits the build. Ping me if you want a walkthrough or need help.

**Comment by jdrossl** [comment]
@sumerjabri @rart maybe this should wait for 3.2 since it could break the ui while we figure out all the files that need to be included

**Comment by rart** [comment]
👍
