### ISSUE TITLE
[Studio and BPs] Search should honor " "

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3160]
## Describe the bug
Searching for a term that's quoted, returns non-explicit matches

## To Reproduce
1. Create a site with Editorial BP
2. Search for `"men"`
3. Note the results contain `women` as a superset

## Expected behavior
Only articles with the string "men" explicitly should be returned.

### Version
3.1.1-SNAPSHOT

### OS
Linux, Ubuntu

### Browser
Chrome

**Comment by jdrossl** [comment]
@sumerjabri all Lucene based search engines will ignore special characters and it is only possible to get exact matches on fields indexed as strings without tokenization

**Comment by sumerjabri** [comment]
@jdrossl can we fix the content model in Editorial to support this?

**Comment by sumerjabri** [comment]
@jdrossl I also notice the same issue with Wordify

**Comment by sumerjabri** [comment]
This is also an issue in Studio's search for the authoring use-case.

**Comment by jdrossl** [comment]
@sumerjabri for every blueprint we need to decide the search requirements:
- list of fields to include in the search
- type of matches on each field (exact or wildcards) to choose the type of the field
- any boosting required (for example boost exact matches in titles over wildcard matches on any other field)

in Studio the logic is different because we are generating the queries based on a list of configurable fields, by default we only search in fields of type `text`, one option is to allow each site to override the list to include other relevant fields

**Comment by sumerjabri** [comment]
per our conversation:
- [ ] Create a document detailing the work: blueprints, fields, updates to the core libraries
- [ ] Divvy up the work
- [ ] Build
- [ ] Test
- [ ] See if any of the docs need to be updated based on the work done

**Comment by jdrossl** [comment]
@rart we will need help updating videocenter & the react version of wordify to implement the same pattern used in groovy https://github.com/craftercms/wordify-blueprint/pull/41

**Comment by rart** [comment]
@jvega190 please update blueprints

**Comment by sumerjabri** [comment]
Verified.
