### ISSUE TITLE
[studio] Ability to Unpublish the Published Content

### ISSUE THREAD

**Issue by hhettiarachchi** [craftercms/craftercms#3164]
As a content author, I should be able to unpublish the published content. At the moment if we want to do this, we have to delete the content item/items and republish again. 

The solution I like would be an option to unpublish a published content item/items So we can still keep the same item in authoring.

**Comment by sumerjabri** [comment]
Rollback a published package. (We can't just rollback a single item because of possible dependency issues.)

**Comment by russdanner** [comment]
Hi! Thanks for suggesting this feature. We understand the need and we're going to address this need long term with "Trash Can" / archive style feature that much more sophisticated "delete" operations.  Since the Trash Can feature is already roadmapped I will close this request to change the current functionality as "Won't Fix" 

_TODAY_ you can unpublish any content item by marking it "disabled". To do so, simply add a checkbox control to your content type with a variable name of 'disabled_b`. When this checkbox is set to true and the item is re-published the delivery engine and search index will _NOT_ return the content.  This is in a sense a logical delete that allows you to remove the content from the site _without_ actually deleting it from the project.
