### ISSUE TITLE
[deployer] delivery: elasticsearch is not indexing documents

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3264]
## Describe the bug
Elasticsearch in delivery is not indexing documents, errors viewing sites.
Index size in delivery
```
curl --silent  -f "http://localhost:9202/_cat/indices?v"
health status index         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   ed-default_v1 2tHAkWNwRRaIrze3vs_efA   5   1          0            0      1.2kb          1.2kb
```

## To Reproduce
1. Create a site from Editorial BP
2. Go to folder `craftercms-delivery/bin` and init the editorial site
3. View de site from delivery env

## Expected behavior
Elasticsearch in delivery index correctly and sIte renders successfully.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
tomcat log in delivery when the site is accessed https://gist.github.com/yacdaniel/9ebd8a9a785e6f5b09a98192255fece7

### Version
Studio Version Number: 3.1.1-SNAPSHOT-9a463e
Build Number: 9a463ea72c518a2e163085c15da31bebd67a514e
Build Date/Time: 07-04-2019 08:50:07 -0600

### OS
Linux

### Browser
Chrome/Firefox

## Additional context
{{Add any other context about the problem here.}}

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 this issue is happening because there was a small change when the index is created/deleted:

before we had a `indexIdFormat` with a default value of `%s` (meaning only the siteName)
https://github.com/craftercms/deployer/pull/137/files#diff-fcdf3ae0c191e34f6d59257d266ea6e2L244

now instead of the format we are using the target id that always includes the environment
https://github.com/craftercms/deployer/pull/137/files#diff-0a80b6254d63dbdf2ef6e742c159a46eR64

for authoring the format matches the target id and that is why only delivery is failing

should we move the `indexIdFormat` into the new hooks or set the deployer to always use the target id format?

**Comment by avasquez614** [comment]
@jdrossl I already did a fixed for this issue. The create index now uses the `indexIdFormat` too. I will take this ticket and assign it back to Yac when we merge the PR.

**Comment by yacdaniel** [comment]
Verified fixed.
