### ISSUE TITLE
Deployment creates major versions with admin username

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#328]
Environment: Alfresco Repo

When a user saves a contents Studio creates a minor version with the current username, however, when a content is published, the system creates the major version with 'admin' username. 

<img width="528" alt="screen shot 2016-12-28 at 1 35 48 pm" src="https://cloud.githubusercontent.com/assets/4325885/21528731/a34ae4f2-cd02-11e6-8d13-883f0f5ce3f3.png">

After publishing the content

<img width="527" alt="screen shot 2016-12-28 at 1 36 11 pm" src="https://cloud.githubusercontent.com/assets/4325885/21528741/b045db1c-cd02-11e6-83e2-b03aa430a5d7.png">

It should keep the username who made the last change deployed.

**Comment by dejan-brkic** [comment]
@russdanner 
We need to discuss this issue. I have spent some time trying to find some workaround, but seems we will not be able to fix issue. It is due to background job and accessing alfresco through CMIS. Every update sets lastModifiedBy value to a user/alf_ticket used to execute service call. Possible workaround would be disabling audible aspect and setting property manually on publishing / creating major version.

**Comment by russdanner** [comment]
@dejan-brkic: I am digging around as well.  There is does not seem to be a CMIS equivalent to RunAs and I don't want to build something that assumes mechanics in the repository below.

Perhaps the answer for us here is to Amend the user detail to the comment.
Also I think it best we recommend a user be created for jobs rather than the Admin account.  "Crafter", "Studio", "Deployment" Something like that.  

Option one:  Comment is "Deployed on behalf of USERNAME, SUBMISSION COMMENT"
Option two is put the details in the comment but the UI uses them to normalize the display

**Comment by russdanner** [comment]
@dejan-brkic Assigned for comment.  Would you like to meet and discuss?

**Comment by russdanner** [comment]
Using work around:
Submitted By USERNAME: COMMENT
