### ISSUE TITLE
[studio-ui] Update font awesome to version 5

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3484]
**Is your feature request related to a problem? Please describe.**
It would be nice to get some more choices for icons that we can use in Studio.  Version 5 of font awesome has more icons we can choose from, such as `fa-baby` or `fa-baby-carriage` 

**Describe the solution you'd like**
Update font awesome to version 5

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rart** [comment]
@russdanner @sumerjabri with plugins in mind, this ticket gets more value. However, instead of upgrading font awesome (FA), I think we should use [Material Design Icons (MDI)](https://material.io/resources/icons/?style=round). The reasons being:
1. Material design is the design system we chose/are using.
2. Our React UI library has deep integration with it.
3. All of the MDI icons and variants are free and available to use vs font awesome only a subset of their variants (2 out of 5) and icons are available for free use
4. If someone reaaaaally wants to use font awesome, they can use it via plugins. In fact, in a more efficient/better way than us embedding the icon font on Studio (i.e. via SVGs, SVG usage is superior to icon font). Not only that but people can bundle the exact set of icons they wish from FA keep the payload smaller.

Plan would be old UI continues it's course and continues to work with FA, new UI publishes MDIs so people can use them easily on their widgets via baseClass, expandedClass, etc like planned.

Can we make the switch?

**Comment by sumerjabri** [comment]
Starting version 4.0, we will use MDI and drop FA except for the older sites/widgets.
