### ISSUE TITLE
[studio] Studio should indicate remotes that cannot be reached on remotes console

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3497]
**Is your feature request related to a problem? Please describe.**
Studio filters out (does note return as part of the API response and thus does not list via the UI) git remotes that cannot be reached (network, etc) or that cannot be interrogated (authentication/authorization) from the list of remotes.  

To the end-user or API consumer this appears to be a bug and they cannot manage the remote.  To remove or correct it the must manually modify the git configuration and database.

**Describe the solution you'd like**
The backend should return all remotes and for those which cannot be accessed, a reason should be provided.  At a minimum, an administrator should be able to see that there is an issue, read the error message and delete the remote.

**Comment by sumerjabri** [comment]
@rart I think design-wise, the repos should always be listed, and broken repos should be marked as such in the UI. What do you think?

We have 4 types of repos:

1. Repos in local git (disk) and in database (db) and are reachable <== these are great and work
2. Repos in disk and db, but unreachable <== these should show up and have repo operations disabled because they don't work. The user can delete these if they want. Editing is not possible at this time (think cluster of Studios).
3. Repos in db but not on disk <== BE should re-init these and fix them <== this is BE work
4. Repos in disk but not in DB <== BE should add these to DB and fix them if possible (they may be unreachable) <== this is BE work

Design-wise, everything ends up as #1 or #2 above.

@rart let me know your thoughts and attach a visual design. We will then route the ticket this way:
1. BE work
2. UI work
3. QA automation
4. Documentation

**Comment by rart** [comment]
Since there are no associated/link PRs, just wanted to comment to record that this was worked a while ago (05/20). The list_remotes API already returns "reachable" and "unreachableReason" and the UI already uses and displays.

Is there anything pending here?

https://github.com/craftercms/studio-ui/pull/1784
https://github.com/craftercms/studio-ui/pull/1785

**Comment by russdanner** [comment]
Confirmed
