### ISSUE TITLE
[engine] Page types are listed under components object in graphql schema

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3522]
## Describe the bug
Page types are listed under components object in graphql schema
<img width="1204" alt="Screen Shot 2019-10-11 at 1 31 05 PM" src="https://user-images.githubusercontent.com/169432/66672734-f71b7a00-ec2c-11e9-89d7-3f475b0a7734.png">

## To Reproduce
1. start site based on editorial
2. use graphiQL schema explore to expand the components type and see page types listed

## Expected behavior
Page types should not be listed under components 

### Version
Studio Version Number: 3.1.4-SNAPSHOT-70ee24
Build Number: 70ee247b9f932f18a5eba9ebd29bd9573513641f
Build Date/Time: 10-09-2019 10:01:20 -0400

### OS
Any

### Browser
Any

**Comment by jdrossl** [comment]
Turns out this was not a bug, that's how GraphiQL displays all known implementations for a given `interface`, when one of those is selected in the explorer a `fragment` is added to the query:

![Screen Shot 2019-10-14 at 9 54 18 AM](https://user-images.githubusercontent.com/1236955/66765225-b14af580-ee68-11e9-925a-9b02741b2f94.png)

**Comment by russdanner** [comment]
Got it. Confusing but that's the tool.  I guess our only option would to find someway to further subclass items as component in these scenarios.
