### ISSUE TITLE
[studio] Marketplace bp sites pages are displayed incorrectly when different sites exists, depending on which site was created first

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3540]
## Describe the bug
Marketplace bp sites pages are displayed incorrectly when different sites exists that uses say css files of the same name, depending on which site was created first

## To Reproduce
1. Create a site using the `Art Showcase` bp from the marketplace.  Below is how the site looks like after creation:
![Screen Shot 2019-10-16 at 11 56 27 AM](https://user-images.githubusercontent.com/25483966/66937828-2146b080-f00e-11e9-921d-72048fed9d56.png)

2. Create a site using the hotel bp from the marketplace.
3. Click on the `Main Menu` and preview the `Art Showcase` site created from step 1.  Notice how the site looks now:
![Screen Shot 2019-10-16 at 11 53 08 AM](https://user-images.githubusercontent.com/25483966/66937960-54893f80-f00e-11e9-833f-f0f85fddfaa5.png)

## Expected behavior
Previewing art showcase or hotel sites, etc should not be affected on which site was created first

## Screenshots
Here's a short clip:
https://www.loom.com/share/f4d909d7549640b196e62aa7cb143c39

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
Studio Version Number: 3.1.4-SNAPSHOT-31df36
Build Number: 31df362f307966926633b458806695069f844f77
Build Date/Time: 10-16-2019 10:01:14 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
This is similar to this ticket: https://github.com/craftercms/craftercms/issues/3010

**Comment by sumerjabri** [comment]
@rart please design the cache-busting mechanism we discussed and assign to your team.

**Comment by rart** [comment]
@jvega190 

Overall, strategy is adding site name as a QS param

```ftl
<link 
  rel="stylesheet"
  href="/static-assets/css/main.css${modePreview?then("?crafterSite=${siteContext.siteName}", "")}`
/>
```

For developer support, create macros, similar to iceAttr, componentAttr, etc which would do this automagically for devs - these macros are on the studio-suppor ftl on engine.

We should have a `@studio.script` macro and `@studio.css` macro. Each would receive `file` and write the script or link tag with the above qs interception. The macros should consider whether the path contains a QS and use `&` instead of `?` in that case.

The macros would become also a convenience for writing scripts and link tags. Assume `/static-assets/css` as the base for `@studio.css` and `/static-assets/js` as the base for `@studio.script`. The macro would accept an additional optional param `base` which would override this default and modify the concat path.
- Could these defaults come from configuration (e.g. yaml file) and served via `envConfig`?

The above imperative example would be written using the macro like...
```ftl
<@studio.css file="main.css">
```

**Do test this is indeed the issue prior to implementing this feature.** You may do this by using the imperative code snippet.

----
When done, assign to @alhambrav for documentation. We should document both the imperative approach and the macros.

**Comment by sumerjabri** [comment]
@jdrossl please reach out to me to discuss a solution.
