### ISSUE TITLE
[studio][studio-ui] Add translations for global menu items and update tab title with navigation

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3666]
## Describe the bug
Global Menu items don't have translations. The label is hardcoded and not internationalized, comes from [/studio/api/2/ui/views/global_menu.json](https://app.swaggerhub.com/apis/craftercms/studio/3.1.4.8#/ui/getGlobalMenu)

As you switch between options, the tab title is not updated.

## To Reproduce
1. Check Global Menu items with a language different than English
2. Navigate to different options and check tab title

## Expected behavior
Global Menu items should be translated to the current language

Tab title gets updated as you navigate

## Screenshots
Spanish language with English Global Menu items
![image](https://user-images.githubusercontent.com/6722074/68698882-83300280-0547-11ea-8bb2-7a3e9d861c19.png)

## Logs
N/A

### Version
`3.1.4-SNAPSHOT`

### OS
Any

### Browser
Any

## Additional context
Related to https://github.com/craftercms/craftercms/issues/3658

**Comment by rart** [comment]
@jvega190 

On `studio` repo, `global-menu-config.xml` file, add new element `<key>`. This key is what the UI will read - instead of label - and pass it through `formatMessage` for translation. If key is not present in the translations table, the `<label>` value should be the fallback.

Though won't be used at this time, add attribute `lang="en"` to the label elements on all menu options.

For quick testing, you may try working in your crafter install on (not sure if it will refresh without server restart, but worth trying).
`crafter-authoring/data/repos/global/configuration/global-menu-config.xml`

**Comment by jvega190** [comment]
[studio-ui] https://github.com/craftercms/studio-ui/pull/1491
[studio] https://github.com/craftercms/studio/pull/1845

**Comment by yacdaniel** [comment]
@rart i18n translations are not uploaded here, please assign back when you update the translations needed here.

**Comment by rart** [comment]
@yacdaniel translations updated.

Follow https://github.com/craftercms/studio-ui/pull/1538 for merge.

**Comment by yacdaniel** [comment]
@jvega190 please check this:

When the user changes the language and goes to the Sites page, the global menu language is not updated, but Studio does. Reloading the browser(F5) updates Global Menu.

![language](https://user-images.githubusercontent.com/6722074/73306286-8307e080-41e1-11ea-86b8-43a7a62ecf60.gif)

**Comment by jvega190** [comment]
https://github.com/craftercms/studio-ui/pull/1544

**Comment by yacdaniel** [comment]
Verified fixed, found an issue while changing language in the account setting https://github.com/craftercms/craftercms/issues/3799
