### ISSUE TITLE
[studio-ui] Studio search should use descending order by default

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3741]
## Describe the bug
With the new  `Sort By` **Relevance** as default, higher the `_score` means more relevant, right now the `Sort Order` is by **Ascending**  which shows first the less relevant items.  The search results should have the `Sort Order` **Descending** as default, the first element in the list is the most relevant.  

### Version
`3.1.5-SNAPSHOT`

## Additional context
Sort By Relevance as default: https://github.com/craftercms/craftercms/issues/3693

**Comment by rart** [comment]
@yureii00 when the selected sort by is "Relevance" flip the underlying values of the sort order control, so that the UI would read "Sort by relevance in ascending order" but for the backed it means "sort by score in descending order".

The flip should occur every time "relevance" is selected deselected. Only relevance would present this behaviour.

**Comment by yacdaniel** [comment]
Verified in develop and 2019 branch.
