### ISSUE TITLE
[studio] Bulk publish does not capture deletes done via git

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3784]
## Describe the bug
Deletes performed by Git are not published when bulk publishing

## To Reproduce
1. Create a site based on editorial. This will publish all content in sandbox
2. Via git console, in the sandbox:
```
rm -rf /static-assets/js
git add --all .
git commit -m "delete via git"
```
4. Wait for git sync i logs:
```
[INFO] 2020-01-29T18:42:57,492 [Studio_Publisher_Thread_Pool5] [site.SiteServiceImpl] | Done syncing database with repository for site: editorialcom fromCommitId = eafba555c3591edaeacc946e4b01b1369841b761 with a final result of: true 
[INFO] 2020-01-29T18:42:57,492 [Studio_Publisher_Thread_Pool5] [site.SiteServiceImpl] | Last commit ID for site: editorialcom is 8899d4f4730d4a43a31718457e14903dcd21ff37 
```
5. Check publish: Note the '/static-assets/js' folder still exists.
6. Bulk publish `/`
7. Wait for bulk publish to complete, note '/static-assets/js' is still there

## Expected behavior
Bulk publish should publish deletes faithfully

## Screenshots
N/A

## Logs
N/A

### Version
```
Studio Version Number: 3.1.5-SNAPSHOT-6bf700
Build Number: 6bf700e4a664554e314ccc4bddbea24236e03ddc
Build Date/Time: 01-29-2020 12:39:08 -0500
```

### OS
Any

### Browser
Any

**Comment by sumerjabri** [comment]
Will be addressed via the new recycle bin.

**Comment by jrosler** [comment]
The issue is around using this as a deployment script for deploying a build update. If you address this as part of recycle bin functionality, we may want a way to work around that. In general my use case is to deploy a site build to an existing site through a tarball. In general, a script removes current content in sandbox, untars the build content into the sandbox, and then does a git add -A and git commit -a "new build". Someone verifies the build in the preview site and then performs a bulk publish to /. Currently that bulk publish doesn't remove content from the delivery sites unless a publish is done to the commit ID and not /. I want to make sure that we have a way to solve for this that doesn't require the commit ID if possible.

**Comment by sumerjabri** [comment]
@jrosler Yes, the solution (which is part of recycle bin) is to treat delete operations like a publishable event. No longer will deletes cause immediate publishing. That will address this issue directly and you can do what you describe as `deletes` become part of the package that gets published.

**Comment by russdanner** [comment]
Just a note here that publish via Commit ID can be used to push the delete to a publishing target.
