### ISSUE TITLE
[studio-ui] Sidebar Browse Widget

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3851]
Please build a new sidebar browse widget. The design is:
![image](https://user-images.githubusercontent.com/3931908/75479744-085feb80-596e-11ea-9408-8aa895d266e8.png)

Please use the API:
https://app.swaggerhub.com/apis/craftercms/studio/3.1.6.3#/content/getChildrenById
or
https://app.swaggerhub.com/apis/craftercms/studio/3.1.6.3#/content/getChildrenByPath

This ticket depends on the API implementation.

To retrieve the children. You may ignore the localization in the initial implementation and add that afterward.

**Comment by sumerjabri** [comment]
Pending the switch to the new API, which is pending this ticket: https://github.com/craftercms/craftercms/issues/4359

**Comment by rart** [comment]
@jvega190 

Still seeing `website` instead of "Home" on the breadcrumbs. Oddly, only in development mode.
![Group 7](https://user-images.githubusercontent.com/3928341/105471699-532bd580-5c9b-11eb-8057-18f2b3171ed9.png)

Pagination data not correctly set on all widgets.
![Group 8](https://user-images.githubusercontent.com/3928341/105471697-51faa880-5c9b-11eb-8e63-c3ef34cbaf94.png)

Please test pagination with the service (e.g. by modifying the minimum items or what ever you need to see it working).

**Comment by rart** [comment]
@aachavarria 
- there is no loading state in between loading different directories.
- please keep ticket until get_children issues are solved and we've tested with those things too (e.g. excludes)

**Comment by rart** [comment]
Completed.
