### ISSUE TITLE
[studio] Rename `environment` element in `Blob Stores` configuration

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3914]
In support of this ticket: https://github.com/craftercms/craftercms/issues/3878, please rename `environment` element in `Blob Stores` configuration.

@russdanner will decide on what to use for the name

**Comment by russdanner** [comment]
I think we need to be consistent with the terminology we have chosen elsewhere.
"publishing-target"
```
            <mapping>
                <publishing-target>live</publishing-target>
                <bucket>my-delivery-bucket</bucket>
            </mapping>```

**Comment by jdrossl** [comment]
@sumerjabri @russdanner I tried to avoid using `bucket` because it sounds S3 specific, I know it is the only implementation for now but if we add something like webdav later we will have to use `bucket` even if it doesn't make sense in that context. What do you think about `publishingTarget` & `storeTarget`?

**Comment by jdrossl** [comment]
@sumerjabri @russdanner I think we should not repeat `storeId` because the store itself already has an `id` and the blob files also have a `storeId` to reference it, what do you think about this:
```
<mapping>
     <publishingTarget>preview|staging|live</publishingTarget>
     <storeTarget>my-delivery-bucket</storeTarget>
</mapping>
```

**Comment by sumerjabri** [comment]
Approved.

**Comment by alhambrav** [comment]
Verified.
