### ISSUE TITLE
[docs] Update the Engine Site Security documentation

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#3992]
Since introducing Spring Security in Engine, along with SAML 2, the way security in Engine has changed. For example, the `profile` object is not available anymore in Groovy (when not using Crafter Profile directly), and now the `authToken` object replaces it. Please update the documentation in https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-site-security-guide.html to reflect this. 

- Create 2 separate documents for Spring Security and Crafter Profile. In each, specify how to do Authentication (Registration, Login, and Logout) and Authorization, with examples.
- Update https://docs.craftercms.org/en/3.1/site-administrators/engine/engine-site-security-guide.html to have references to these 2 new documents.

**Comment by jdrossl** [comment]
@avasquez614 maybe we should meet to define a new layout for the doc, because Login, Logout & Authorization work the same for profile & spring-security, the only difference is Registration that is only supported with Profile or custom services. For the `authToken` maybe we can add a section like "Migrating from Crafter Profile to Spring Security" similar to what we did for ES

**Comment by avasquez614** [comment]
Verified
