### ISSUE TITLE
[docs] Create a Kubernetes specific guide for clustering of Studio

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4040]
**Is your feature request related to a problem? Please describe.**
Create a Kubernetes specific guide for Clustering of Studio

**Comment by asotog** [comment]
Could it be possible to have a chart repository for Crafter CMS on https://helm.sh/ ? Was reading about it, looks quite interesting

**Comment by avasquez614** [comment]
@asotog we've considered Helm, but we are not planning to pursue it in the short term. Creating a Helm for a simple installation is easy, creating one for Crafter is more complicated since the architecture of our installations can vary a lot (single Authoring with embedded cluster, Authoring cluster with external DB, Authoring self-cluster with embedded DB, serverless Delivery, etc.)

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1044 and https://github.com/craftercms/docs/pull/1045

**Comment by russdanner** [comment]
Confirmed
