### ISSUE TITLE
[core][studio] Inject element's source descriptor during merging

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4093]
Merged artifacts must include an element attribute indicating the source descriptor if different than the descriptor being loaded (think inheritance).
The attribute name is: `src`

- [x] Update Core
- [x] Update Engine
- [x] Update Studio
- [ ] Update ICE to become aware of `src` element and leverage it to better author

**Comment by jdrossl** [comment]
@rart the new API for studio is ready

**Comment by rart** [comment]
@jdrossl 
- Can't find this on swagger?
- Is it possible to send flatten=false through the studio API? Can we propagate the options to the engine API?

**Comment by rart** [comment]
@SumerJabri we didn't include the `flatten` option on the studio side. This disables the possibility of doing progressive loading of the content items. 

PageBuilder is covered as this, by default, returns the whole tree, flattened but Form engine would benefit from the reduced/progressive on-demand payload. Also, since this is published as part of the npm studio-ui package, having the option provides additional versatility for the community to create (e.g. studio plugins) in whatever way it fits best for their use case.

I don't see value in hiding the option.

Can we include it?

**Comment by sumerjabri** [comment]
@rart yes
@jdrossl please make flattening options. @rart is saying that it's permanently on right now for Studio's version of this API.

**Comment by rart** [comment]
As an additional item, please add an additional attribute containing the content type id of the source file: `crafter-source-content-type-id`). For example:

```xml
<header_o 
  crafter-source="/site/website/crafter-level-descriptor.level.xml"
  crafter-source-content-type-id="/component/level-descriptor"
>
    <item>
      ...
```

**Comment by sumerjabri** [comment]
@jdrossl please work on this after CLI and then assign back to @rart 

@rart this remains a low priority ticket from your perspective

**Comment by jdrossl** [comment]
@rart both updates are merged now

**Comment by rart** [comment]
PageBuilder's ICE now recognizes inherited zones and allows editing the level descriptor.
