### ISSUE TITLE
[studio] Publishing child item doesn't change its parent's state to system processing

### ISSUE THREAD

**Issue by hlim** [craftercms/craftercms#425]
Steps to reproduce

1) Create a content
2) Create another content under the first content
3) Select the child content and click 'Approve & Publish' 

Error 1: UI should display the parent item as it will be pulled in automatically since the parent item is new.

Error 2: After submission, the parent item stays 'Edited' state but will eventually changes to 'Live' state as it is published together with the child item.

**Comment by russdanner** [comment]
The state is changed for parents but Icon is wrong.  I am closing this because I think that (status icons not updating without refresh) is a different (already logged bug)

<img width="684" alt="screen shot 2017-06-22 at 2 48 41 pm" src="https://user-images.githubusercontent.com/169432/27450598-2894bb38-575a-11e7-82d9-4ddee4c6bf38.png">
