### ISSUE TITLE
[studio-ui] Add spell check attribute to TinyMCE2 and 5

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4324]
**Is your feature request related to a problem? Please describe.**
TinyMCE only allows the browser to spell check (using the built in OS spell checking) if a configuration is set.

**Describe the solution you'd like**
Turn on browser spell checking in TinyMCE 2 and 5
https://www.tiny.cloud/docs/general-configuration-guide/spell-checking/

**Comment by jvega190** [comment]
@russdanner added the spell check, is configurable via the content type editor, default to true.
For tinymce5 when enablling spell check the custom context menu needs to be disabled in order to show the recommendations on the browser's context menu, for tinymce2, custom context menu is already disabled

**Comment by sumerjabri** [comment]
@rart @jvega190 should this ticket be routed back to @russdanner for validation?

**Comment by russdanner** [comment]
Confirmed!
