### ISSUE TITLE
[studio] Renaming a file to the same name with a different case corrupts the database

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4335]
## Describe the bug
Renaming a file to the same name with a different case corrupts the database 

When you have a commit that contains a rename operation where the rename is just a case change in the file name the database-git sync process ultimately removes the record for the item from item metadata and item state tables. 

When no record exists for a path in item metadata or item state the publisher will stop with an exception and leave  branch ENV_in_progress in place with unfinished work.

## To Reproduce
1. Create a site based on editorial
2. in the database prove that a record exists for a file
```
select commit_id, path  from item_metadata where path="/static-assets/images/strawberries.jpg";
```

3. In the sandbox execute the following commands
```
cd static-assets/images
git mv -f strawberries.jpg Strawberries.jpg
git add --all .
git commit -m "do a rename"
```
4. Wait for the sync to run (see logs for confirmation)
5.  Check the database and see there is no result. Note you can alter the case of the filename, there is no record regardless of case. 
```
select commit_id, path  from item_metadata where path="/static-assets/images/strawberries.jpg";
```
You have now replicated the root cause. Any operation that uses the data in item metadata or state etc will fail or return incorrect information.

For example in previous versions to 3.1.10
If you publish a commit ID that contains the path of the renamed object but this record does not exist the publisher will throw an error and halt mid process.

## Expected behavior
Changing the case of a file name/path should not result in a missing record(s) in the database

## Screenshots
https://www.loom.com/share/3adf1be3f8d44b66b57991f0085e9b24

### Version
```
Studio Version Number: 3.1.10-SNAPSHOT-26a0e4
Build Number: 26a0e408442a51f6d4d7c809d26be42f2f254e9c
Build Date/Time: 10-06-2020 14:13:58 -0400
```

### OS
All

### Browser
N/A

**Comment by dejan-brkic** [comment]
The issue is caused by the database being case insensitive.

There are 3 options to make queries case sensitive:
1. make only specific queries case sensitive e.g.
`SELECT * FROM `table` WHERE `column` = BINARY 'value'`

2. make specific tables/columns case sensitive e.g. 
`ALTER TABLE <table_name> CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin`
`ALTER TABLE <table_name> MODIFY <column_name> VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin`

3. make the whole schema case sensitive e.g.
`ALTER DATABASE <database_name> CHARACTER SET utf8 COLLATE utf8_bin`

With option 1 we can address the delete record issue by deleting with case sensitive path. The problem needs additional patching in source code because a move in the git command is translated to create + delete in Sync DB operations. Case sensitive delete would remove the proper record, but create operation is processed before delete, and insert a new record (case sensitive path) is failing due to duplicate index exception (case insensitive column and schema)

Long term solution is either option 2 or 3.

**Comment by dejan-brkic** [comment]
Short term solution:
https://github.com/craftercms/studio/pull/2212
https://github.com/craftercms/studio/pull/2213

**Comment by sumerjabri** [comment]
@russdanner please don't close. Simple verify for 3.1.11 and then mark as completed in 3.1.x. Switch the milestone to 3.2.1 for us to pursue the longer-term solution in 3.2.x.

**Comment by russdanner** [comment]
Confirmed
