### ISSUE TITLE
[commons] CORS filter issue

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4389]
## Describe the bug
The CORS filter is adding `*` in the response `Access-Control-Allow-Methods` & `Access-Control-Allow-Headers` headers that can lead to the browser rejecting the requests.

## Expected behavior
When the configuration contains `*` the response should return a list mirroring the headers & method of the request

### Version
3.1.x & 3.2

**Comment by jdrossl** [comment]
@rart please help checking that CORS continues to work as expected, I used video-center to test but maybe you can think of more tests cases and even help Yac automate some of them.

**Comment by rart** [comment]
@jdrossl `<accessControlAllowMethods>GET\, POST\, PUT\, OPTIONS</accessControlAllowMethods>` doesn't work apparently due to the spaces.

**Comment by rart** [comment]
@jdrossl looks like CORs policy is not applied to static-assets. Is this expected?

**Comment by rart** [comment]
Upon further inspection, it looks like the issue is the lack of _credentials_ when using on stylesheet imports (e.g. `@import`, `url('...')`). Cookies aren't sent, hence crafterSite is not known and request fails.

In this case, shows as a CORS issue because the default site probably doesn't have any CORS config but it would otherwise 404.

The solution is to include crafterSite=theSiteId on the stylesheet imports, like so:
`url('../fonts/fontawesome-webfont.eot?crafterSite=wordify')`

This is definitely subject for the docs, if not already there, @alhambrav.

I think this might not happen in production deployments as those are usually directly mapped to a site. But it might still happen on authoring, staging and development environments that don't have such mapping. 

The biggest inconvenience here, is that developers are forced to edit third party libs — like in this case fontawesome stylesheet — to include the `?crafterSite=...`. Alternatives would be welcome. @sumerjabri
