### ISSUE TITLE
[studio-ui] Receptacles datasource is not filtering options selected in configuration

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4393]
## Describe the bug
The receptacles datasource has a list of configurable options for adding content (via search, browse, embedded, shared). Right now if any of those options are disabled it still shows the option on the form.

## To Reproduce
1. Go to Site Config -> Content Types and edit a type
2. Add a receptacles datasource and unselect one of the options (e.g. Enable Browse)
3. Go to the corresponding form and click on add (in the control that has the receptacles datasource associated).
4. See that the browse still shows up.

## Expected behavior
Unselected options in the datasource configuration should't show up in the form editor.

### Version
Crafter CMS 3.2.x

**Comment by jvega190** [comment]
depends on this PR too https://github.com/craftercms/studio-ui/pull/2017

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation

**Comment by yacdaniel** [comment]
@jvega190 please check the following, some receptacle properties are not populating the data source in the form editor
![image](https://user-images.githubusercontent.com/6722074/105512094-4fe21b00-5c96-11eb-9013-d84e954d09ab.png)
![image](https://user-images.githubusercontent.com/6722074/105512123-596b8300-5c96-11eb-8ea3-871f295aa113.png)

Same issue when `Enable Browse` is checked.

**Comment by rart** [comment]
@yacdaniel @jvega190 The problem is that `enable browse` and `enable search` are really only valid if you enable/allow shared components. Otherwise it's sort of a violation of how the datasource was configured. 

Optimally we would only show or enable those checkboxes when "allow shared is enabled". We don't have a generic mechanism for this on the form builder; @jvega190, let's see if it's doable without incurring in poor coding. Otherwise, I don't think search or browse should show up unless "shared" are enabled.

Another good tweak would be to add a message indicating no options are available for adding.

**Comment by yacdaniel** [comment]
Verified fixed. A message indicates when `enable browse` and  `enable search` can be enabled. 
![image](https://user-images.githubusercontent.com/6722074/107240050-1b3cc600-69ef-11eb-83f3-e51446b62b1d.png)
