### ISSUE TITLE
[studio] Add user properties store and API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4423]
Add a new table: user_properties (change the name as needed)
The table will carry:
* id (property ID)
* user_id (FK) (index)
* site_id (FK) (index) -- remember global is site_id 0 aka system
* property_key (index)
* property_value (text)

Spec out an API that lets the UI CRUD these properties. This API is only available to the user to CRUD *their* properties.

**Comment by rart** [comment]
@sumerjabri wondering if adding a nullable "siteId" schema field would be useful so that if a site is ever removed, the table could be purged of stuff that won't be needed anymore. The backend could remove all site entries when a site is deleted. 

**User** preferences — non-site-specific — would leave that field empty.

**Comment by sumerjabri** [comment]
@rart added, but not nullable. Global is set to the global site ID (much like some of our existing UI elements (see audit viewer)).

**Comment by rart** [comment]
@sumerjabri Got it. Please confirm: site_id is the site string name (e.g. "editorial") or is it the actual DB id?

We don't keep the db id as readily available as the site id name we use for everything so preferrably it is the string site id.

**Comment by jdrossl** [comment]
@rart  The db will use the numeric id, the service can still receive the usual string id

**Comment by jdrossl** [comment]
@rart the backend is ready

**Comment by sumerjabri** [comment]
@rart please close if this is complete.
