### ISSUE TITLE
RTE box fit to size.

### ISSUE THREAD

**Issue by sandeepkadyan** [craftercms/craftercms#447]
Hi Team,

One of the page have issue with RET box fit to size.
Can you please know how can i fix this.

**Comment by russdanner** [comment]
Hi Sandeep,
You can adjust the width of an RTE via the Content Type definition.  
1. Go to the admin console
2. Go to content types 
3. Open existing type and choose your type
4. Find the RTE component you want and click on it.  This will allow change the properties area to show the properties for the RTE.  Now you can set a different width.

These docs may be helpful:
* http://docs.craftercms.org/en/stable/developers/content-modeling.html
* http://docs.craftercms.org/en/stable/developers/content-modeling.html#content-type-model-definition
* http://docs.craftercms.org/en/stable/developers/form-controls/form-rte.html#form-rte

Note it is a best practice to try and configure the RTE width the same as the width on the site/experience so that the wrapping is as close as possible.
