### ISSUE TITLE
Allow System.nanoTime() in groovy sandbox by default

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4527]
**Is your feature request related to a problem? Please describe.**
Performance tracking can't be done accurately with System.currentTimeMillis(). nanoTime() is preferred.
https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime--

**Describe the solution you'd like**
Add nanoTime to the sandbox by default

**Describe alternatives you've considered**
no precise workarounds. currentTimeMillis is as good as we can get.

**Additional context**
n/a

**Comment by jdrossl** [comment]
hi @tfield , we can't enable the method by default because it was identified as a possible attack vector. However you can enable it in your installation if needed as described in our [documentation](https://docs.craftercms.org/en/3.1/developers/projects/engine/api/script-sandbox-configuration.html#using-a-custom-blacklist) 

Another option is to use a third-party class to handle time calculations, for example [Spring's StopWatch](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/StopWatch.html)
