### ISSUE TITLE
[deployer] Limit document size in Elasticsearch

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#4727]
## Describe the bug
When Crafter flattens documents for insertion into Elasticsearch, the resultant document can be extremely large.  Large docs can cause problems (up to and including crashes) in Elasticsearch. Crafter should measure the document size and add a warning to the logs if the size is above a limit that could be problematic for Elasticsearch.  The limit should default to something sensible, but be configurable, in case the sysadmin has adjusted Elasticsearch config to tolerate larger documents.

This will allow developers to pre-emptively address scalability problems before they go to production.

## To Reproduce
1. Create a content item with references to other content items
2. Attach other content items to the first one
3. Search for the document in Elasticsearch
4. Look at the size of the returned document
5. Adjust sizes/nesting to the point where the document grows to a few megabytes or more
6. Watch the deployer and elastic logs for errors

## Expected behavior
A warning appears in the studio catalina.out if the flattened document is very large.

### Version
3.1.10

**Comment by jdrossl** [comment]
@sumerjabri there are multiple limitations to implement this feature:

1. Studio is unaware of XML flattening, it only handles individual files in the repository
2. During indexing the Deployer uses a map with the flattened XML to create the index request, so the final size of the document is also unknown because the ES client handles serialization

As an alternative I would suggest adding a configurable limit to trigger a warning after writing individual files in Studio (it can't be before because we use streams so the size is also unknown)

**Comment by sumerjabri** [comment]
@tfield the size limit in ES is **_100MB_** per document. It seems that binary content is being base64'd and placed into textual content. Images and other binaries should be stored as binaries and referenced by content.

ES is failing outside of our sphere of control. We flatten the content and, without knowing the size (because we can't), we feed that data structure (Map) to ES Client which feeds the server. The ES server fails.

There is no way to know how the flattened XML will ultimately get composed (that's up to the authors and how they compose pages), and so we cannot warn upfront that content is too large.

This, fundamentally, is a content problem. Binary content should not be base64'd into textual content. While Crafter Studio and Engine don't care and will ferry it for you, ES does and will fail.

Additionally, not having binary files as binary files circumvents CDN and other cache mechanics (including browser cache) that are built/optimized to deal with this specifically.

Happy to discuss this more if required.
