### ISSUE TITLE
[studio-ui] Edit of item in NEW state transitions to EDITED state

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#4830]
## Describe the bug
An edit of a new item transitions the state from New to Edited

The point of the New state is to indicate the item has never been published
The point of the Edit state is to indicate that the item has previously been published but is now edited (relative to the Live state)

## To Reproduce
1. Create a site based on editorial
2. Note the home page is in a NEW state (because we do not auto-publish on create)
3. Edit the home page and refresh the screen (to ensure you are not seeing a cached state)
4. Note the home page is now edited

## Expected behavior
An item in a new state should remain in the New state until it is published to the Live target

## Screenshots
N/A

## Logs
N/A

### Version
4.0

### OS
Any

### Browser
All

**Comment by dejan-brkic** [comment]
Incorrect description of issue or feature.
There is no NEW nor EDITED state. The state is a bitmap now with several flags. The NEW flag indicates whether content has been published or not. The MODIFIED flag indicates whether content has been modified since creation or since last publish.
Requested expected behavior is not aligned with the state bitmap design/feature

**Comment by sumerjabri** [comment]
@rart please make the New state have precedence over the Edited state.

**Comment by russdanner** [comment]
Confirmed
