### ISSUE TITLE
[studio-ui] Issues with plugin management

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4851]
## Describe the bug

1. In the installed plugin list the URL is regular text instead of a link
2. The files created by a plugin are not visible in the Site Explorer unless you refresh the page (seems like once a folder is opened the result is cached and there is no way to see new changes this could also be an issue with concurrent users)

## Screenshots
![plugins](https://user-images.githubusercontent.com/1236955/125698621-43e7225a-b4c0-4428-8f40-f7cf7c70cc44.gif)

### Version
4.0.0-SNAPSHOT

### OS
Ubuntu 20.04.2 LTS

### Browser
Chrome 91.0.4472.114

**Comment by rart** [comment]
You needn't refresh the page. The widget can be refreshed using widget menu's refresh. I recognize this is often missed by users so far, we certainly need to add some widget introduction/training for users.

Nevertheless, we can do something to improve this particular use case. @aachavarria please add a plugin installed system event which PathNav & TreeNav should listen for a refresh. 

I think plugins can add pretty much all paths should refresh since plugins can add content, assets, scripts and templates. I would imagine taxonomies too? @jdrossl can you confirm.

**Comment by jdrossl** [comment]
Verified
