### ISSUE TITLE
[plugin][google-maps] Create a plugin to allow authors to drop a Google Maps widget on pages

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4921]
Repo: https://github.com/craftercms/googlemaps-plugin
Start with a good design and a simple implementation with room to grow.

### Tasks
- [x] Design
- [x] Implement BE
- [x] Implement FE
- [x] Test
- [x] Document in README.md within the plugin
- [x] Publish to the Marketplace

**Comment by rart** [comment]
@sumerjabri any available details/requirements on what to do on the UI? @jvega190 please follow up.

**Comment by sumerjabri** [comment]
@rart at a high-level:
* Allow authors to drop a Google Maps widget on pages
* Support PB
* Ask @jdrossl any lower-level tech questions

**Comment by sumerjabri** [comment]
@jvega190 what's next for this?

**Comment by phuongnq** [comment]
* Preview images are not showing 

![image_not_show_01](https://user-images.githubusercontent.com/2996543/129126814-50904cf9-fbb1-4c11-b92e-cdb381cae61f.png)
![image_not_show_02](https://user-images.githubusercontent.com/2996543/129126825-2b97c345-fbf1-435a-919d-f777c83d0efc.png)

* When I put information as following, there is an error displaying Google Maps:

![google_map_setting](https://user-images.githubusercontent.com/2996543/129126885-79481b38-028b-401a-99fc-171a7648942f.png)
![google_map_error](https://user-images.githubusercontent.com/2996543/129126890-539dd3e7-31a5-4488-b80d-f49d8bd1be5b.png)

* Help icon position is not clean

![help_icon_position](https://user-images.githubusercontent.com/2996543/129126944-a4e88994-c3f4-4ef7-b5cb-bada5301a9bd.png)

* Better to have more clear setup description on README.md

What is the configuration file to put the API key to? (seems like we need to put it to "Engine Site Configuration"?)

If possible, add a line similar to this one https://github.com/craftercms/contact-form-plugin#setup to mention about content-type while using the plugin.

* Not sure if this is a bug of Crafter 4.0 or the plugin but if I put the map component to the HTML tag loop of Editorial BP Article Page, when saving a map, the title displays the internal name of the plugin name instead of the article name.

 
![display_name](https://user-images.githubusercontent.com/2996543/129128024-c6d1ec36-7719-4323-8fb3-7b3b8754472f.png)

![display_name_02](https://user-images.githubusercontent.com/2996543/129128028-00870d9e-0b1e-4ed9-b04b-affb7748c908.png)

![display_name_03](https://user-images.githubusercontent.com/2996543/129128029-4f845f93-7257-4e88-9975-b53d76146ffb.png)

![display_name_04](https://user-images.githubusercontent.com/2996543/129128034-718d759e-affa-4798-819f-1dca3f42745c.png)

**Comment by jdrossl** [comment]
@phuongnq for the missing parameter we have link to the API docs, there are a lot of options and I think it's better to have the link than trying to explain everything in the readme https://developers.google.com/maps/documentation/embed/embedding-map#choosing_map_modes

**Comment by phuongnq** [comment]
verified the fix.
