### ISSUE TITLE
[docker-images][docker-compose] Setup Docker branches for Crafter CMS 4.0

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4957]
In https://github.com/craftercms/docker-images:

1. Merge `support/3.1.x` into the `develop` branch
2. Update the based images of Authoring Tomcat and Delivery Tomcat to use the Tomcat image that matches the one being used by Crafter CMS 4.0.
3. Update the base image of Deployer to use the OpenJDK image that matches the OpenJDK version used by Crafter CMS 4.0.
4. Check all images to make sure that the dependencies (installed with `apt-get`) have the appropiate version for the 4.0 code.
5. Make sure you can build the images.

In https://github.com/craftercms/docker-compose:

1. Merge `support/3.1.x` into the `develop` branch
2. Update all the Docker Compose files to use the 4.0 images.
3. Update the Elasticsearch version to match the 4.0 version.
4. Remove all Docker Compose files related to Solr and all Solr configuration.
5. Test Docker Compose.

**Comment by phuongnq** [comment]
@avasquez614 I sent PRs for both.

A note:

* https://github.com/craftercms/docker-images:

Seem like the bundle for 4.0 has directory `crafter-authoring` and `crafter-delivery` instead of `crafter` so I updated build script. If this is not correct, please let me know I will revert the change. Ex: 

```
authoringBundleRoot = "${tempDir}/" + FilenameUtils.getBaseName(authoringBundleUrl) + "/crafter-authoring"
```

* https://github.com/craftercms/docker-compose:

While running delivery, I noticed that it runs in port 9080 internal instead of 8080. So the port mapping setting that works for me is 9080:8080. Maybe I missed some configuration or did we change the way it maps?

**Comment by avasquez614** [comment]
@phuongnq that 8080 in Delivery is expected since we use the Tomcat of the base image without many customizations. Having to map 9080:8080 in your local is expected.

**Comment by phuongnq** [comment]
@avasquez614 Thanks for the verify. There is no issue with PR in docker-compose. Please go ahead and review it.
I added another PR for docker-images as the fact that we are currently hard code the delivery port to 9080. (If we update Crafter 4 to use an environment variable, this PR can be ignored)

https://github.com/craftercms/docker-images/pull/37
