### ISSUE TITLE
[studio][deployer][engine] Support symlinks

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5341]
#### Is your feature request related to a problem? Please describe.
Using symlinks to indicate the latest version of a static asset library/file is a common practice. It would be great if Crafter can support them. Git seems to support symlinks.

#### Describe the solution you'd like
Support symlinks in all modules of Crafter Studio when handling static assets:

- Studio shows the file as a symlink
- Studio can publish the file
- Engine follows the file when servicing the content (including when reading from S3)
- Deployer follows the file when indexing
- Deployer copies and deletes the symlink to/from S3

#### Describe alternatives you've considered
N/A

**Comment by sumerjabri** [comment]
Concerns:
* Studio's modeling of folders in DB
* Dep calc and dep integrity
* Publishing based on the above
* Search and search results as links switch
* What would the UI show? What happens if a user deletes a symlink, what would the UI show?

This is a much bigger deal than it looks. This requires a bigger conversation @avasquez614.

We should consider using the built-in rewrite system to help with this.

**Comment by sumerjabri** [comment]
Will not pursue this.
