### ISSUE TITLE
[studio-ui] ICE is not available for element with a specific set of styles

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5344]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
March 1st, 2022

#### Describe the bug
ICE is not available on elements with style

```
position: absolute;
inset: 0
```

#### To Reproduce
1. Create a new site from an empty BP
2. Edit entry.ftl to have the following content: (Make sure to update model-id to objectId of /site/website/index.xml)

```
<!DOCTYPE html>
<html>
<head>
  <title>app</title>
  <script src="http://localhost:8080/studio/static-assets/scripts/craftercms-xb.umd.js"></script>
</head>
<body>
  <h1
    data-craftercms-model-id="8d7f21fa-5e09-00aa-8340-853b7db302da"
    data-craftercms-model-path="/site/website/index.xml"
    data-craftercms-label="Home"
    style="position: absolute;inset: 0;"
  >
   About Us
  </h1>
  <script>craftercms.xb.initInContextEditing({ path: '/site/website/index.xml' });</script>
</body>
</html>
```

4. In preview mode notice that ICE is enabled but there is no option to edit
5. Note that if we remove the style, ICE is working as expected

#### Screenshots
[{{If applicable, add screenshots to help explain your problem.}}
](https://user-images.githubusercontent.com/2996543/156126014-0de95896-7d96-434e-bdb1-4f2caffc35a2.mp4
)

**Comment by rart** [comment]
We could not reproduce the issue. ICE did show up.

We do see the tooltip popup (that shows the field name and actions) going out of the view port, requiring scrolling to view the whole tooltip. That's a different bug that's not easily addressed now and is a rare thing to have. It happens due to the field/model occupying the whole area of the page and the tooltip positioned only knows how to position above or below the are.
