### ISSUE TITLE
[deployer][studio] Studio and Deployer should be able to recover from .git/index.lock on startup

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5600]
#### Crafter CMS Version
3.1.23 and up

#### Date of Build
N/A

#### Describe the bug
If Studio or Deployer is stopped in the middle of a pull, it can leave a `.git/index.lock`. This happens a lot in servers that are restarted and have Deployer running every 10 secs.

#### To Reproduce
1. Stop Deployer when in the middle of a big pull or create an `index.lock` lock after stopping it.
2. Start the Deployer

After that, the Deployer will be stuck for the target forever until the lock file is removed.

**Comment by jdrossl** [comment]
This can be handled by the same code as https://github.com/craftercms/deployer/pull/354/files since it will also clean the repo, see [deployer](https://github.com/craftercms/deployer/blob/08f7d9bcf4046743593fdd6ca2a8e7de093a20bd/src/main/java/org/craftercms/deployer/impl/processors/git/GitPullProcessor.java#L129) & [studio](https://github.com/craftercms/studio/blob/5dc472a7753ec58c5c6099a8c327aaef04dd4a86/src/main/java/org/craftercms/studio/api/v2/annotation/RetryingRepositoryOperationAnnotationHandler.java#L80)

**Comment by sumerjabri** [comment]
@phuongnq hold off on this. I will discuss with @russdanner and @avasquez614 before proceeding any further.

**Comment by sumerjabri** [comment]
@phuongnq Please update so that the lock is cleaned up on boot of Studio or Deployer, and not per pull. This means cleaning up:

**Comment by sumerjabri** [comment]
@phuongnq we won't merge until the main Studio PR is sent as well. Okay?

**Comment by Euquimides** [comment]
Hi! Updated and re-checked this issue. The `index.lock` files are cleaned upon re-start on sandbox per site, published per site and deployer repo per site. Thank you! Closing this ticket.
