### ISSUE TITLE
[studio] Workflow API's /workflow/publish is returning HTTP 500 when sending request body with non-existent siteId

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5634]
#### Crafter CMS Version
`4.0.1-SNAPSHOT-cde410`

#### Date of Build
`6/13/2022`

#### Describe the bug
When sending a request body that includes a non-existent `siteId` to the `/workflow/publish API`, the response will be a HTTP 500 instead of HTTP 404. 

#### To Reproduce
Use a REST API tool:

1. Set up a request for the APIs, POST /workflow/publish.
2. Fill up the required request body.
3. Add in the `siteId` field of the request body, a non-existent siteId.
4. See error. 

#### Logs
If you send the request body as specified (with a non-existent siteId), you'll receive the following response:
 ```
{
    "response": {
        "code": 1000,
        "message": "Internal system failure",
        "remedialAction": "Contact support",
        "documentationUrl": ""
    }
}
```

#### Screenshots
N/A

#### Expected behavior
The `/workflow/publish API` should return HTTP 404 if the `siteId` doesn't exist.

**Comment by jdrossl** [comment]
@jmendeza we already have a `SiteNotFoundException` that returns the expected error, the issue is that all services need to perform [the same call to trigger the exception](https://github.com/craftercms/studio/blob/221e57d9beba955dbabe20d2e7fe553ed483a9eb/src/main/java/org/craftercms/studio/impl/v1/service/site/SiteServiceImpl.java#L1413), it would be great if we could have a way to trigger the validation early in the controller (maybe a custom validation annotation `@ValidSiteId`). Take a look to see if it's easy to add, otherwise lets just fix this one and keep it as a future improvement

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. It is fixed now, thank you! Closing this ticket.
