### ISSUE TITLE
Studio search result is not displayed in correct sort order of response data 

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5654]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

While searching content with Sort By Last Edit Date, the result order is randomly changed by refreshing the page

### Steps to reproduce

Steps:

1. Create a site from Editorial BP
2. Go to Search and add filters: Sort By *Last Edit Date*, Sort Order: *Descending*
3. Edit some search results and refresh the search page
4. Notice that the order is randomly changed and different from the order of API data

### Screenshots and/or videos

![2022-06-24_08-56](https://user-images.githubusercontent.com/2996543/175451724-a1192eb3-b7a5-4cbe-9f8f-5e62cf2cada1.png)

**Comment by russdanner** [comment]
From @phuongnq 
 The response data from the backend seems correct but the frontend randomly changes the order. This may be due to the render method we are using to render results:
$.each(results.items, function (index, result) {
      CStudioSearch.renderResult(result);
    });
This will render each result and append to HTML so I think it does not guarantee the order.

**Comment by russdanner** [comment]
Investigation shows that this is a result of a permission check while rendering each item.
If the permission is cached the item is rendered right away (in the order it is returned in the result)
If the permission of the item is not cached it is rendered when the check permission check API returns. Thus any item that the UI has not previously cached will return in a non-deterministic order. 

This can be solved by passing the promise a properly ordered container element to render into rather than simply appending the rendered result at the end of the list of cards.

**Comment by phuongnq** [comment]
verified.

**Comment by russdanner** [comment]
Confirmed
