### ISSUE TITLE
[studio-ui] Files with Parenthesis in their name cannot be deleted

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#5675]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

When you upload a file with a parenthesis in its' file name, the file is unable to be deleted.

### Steps to reproduce

Steps:

1. Create a new site based on the editorial blueprint
2. Navigate to Static-Assets
3. Upload a file with parenthesis in the file name `this (will not) work.txt` for example
4. Once the file has been uploaded, right-click and see that there is no option to delete the file 

### Relevant log output

```shell
N/A
```

### Screenshots and/or videos

![image](https://user-images.githubusercontent.com/42217570/177601413-00a91047-55aa-432e-bdfd-6a0d0efc8225.png)

**Comment by jmendeza** [comment]
@sumerjabri the culprit seems to be this regex not matching the files with closing parentheses in the name
https://github.com/craftercms/studio/blob/develop/src/main/webapp/repo-bootstrap/global/blueprints/1000_website_editorial/config/studio/site-config.xml#L163

Notice the pattern is excluding closing parentheses
Because it does not match any pattern, it is treated like a "FILE"
https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v1/service/content/ContentServiceImpl.java#L2192

**Comment by jmendeza** [comment]
Updated asset pattern regex to accept parentheses

**Comment by AndyReiter** [comment]
Confirmed fixed in 4.0-SNAPSHOT.
