### ISSUE TITLE
[studio] Log console throws error 1000 after a wait period

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5779]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you open the log console and let it sit for a period of time, it eventually throws an error in the UI: Error ID: 1000.

### Steps to reproduce

Steps:

1. Go to any site
2. Open the log console
3. Wait long enough (for me this was 100 requests to the log API)
4. See the issue

### Screenshots and/or videos

<img width="1600" alt="Screen Shot 2022-09-09 at 10 56 12 AM" src="https://user-images.githubusercontent.com/169432/189405748-79133de9-9ffc-428f-ba20-a7b7b40bc34b.png">

**Comment by russdanner** [comment]
Dismissing the dialog seems to allow the console to continue logging

**Comment by phuongnq** [comment]
The issue seems because of the Engine proxy responds with a `Transfer-Encoding` and Studio also responds to the client with a new header. This makes a duplication `Transfer-Encoding` and Chrome does not like this when the connection is reset.

![Screenshot from 2022-12-27 15-45-09](https://user-images.githubusercontent.com/2996543/209642193-99af7bf9-4b1e-4f2f-99d7-70f67b9e96bc.png)

**Comment by russdanner** [comment]
confirmed
