### ISSUE TITLE
[studio-ui] inconsistent on how the parentPath macro work with embedded component

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5808]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

While using `parentPath[0]` macro with the parent is an embedded content, there are cases that the value is `undefined` and there are cases that the value is the parent path of the parent of that embedded content. 

### Steps to reproduce

Steps:

1. Create a new site from the following customized Editorial BP: https://github.com/phuongnq/craftercms-parentpath-macro-ed

Note that in this BP:

* In the `/page/article` content type, update the `Left Rail` to be able to be embedded.
![2022-10-04_15-21](https://user-images.githubusercontent.com/2996543/193770497-469f09f9-2238-43de-9184-2e345fd29d58.png)
![2022-10-04_15-22](https://user-images.githubusercontent.com/2996543/193770654-4b04589b-f38b-4559-8e46-f812745a2ccd.png)

* In the `/component/left-rail` content type, update the `components` data source to use `parentPath[0]` macro:

![2022-10-04_15-22_1](https://user-images.githubusercontent.com/2996543/193770989-177264fb-1df5-4656-b0b5-77c01408c199.png)

* There is a `test` article under `/site/website/articles`

2. Click Edit on the `test` article
3. Click Edit on the Left Rail embedded component
4. On the Left Rail open, on Widgets group box, click Add > Browse for Existing - Components
5. Notice that the `parentPath[0]` return `undefined` in the path title
![2022-10-04_15-25](https://user-images.githubusercontent.com/2996543/193771630-90527fcf-77d4-4abc-a990-ff29f771a7af.png)

If we create an article instead, there is no issue:
1. Click to create new article under `/site/webiste/articles` folder
2. Click to add a new embedded Left Rail
3. On the left rail open, on Widgets group box, click Add > Browse for Existing -Components
4. Notice that the `parentPath[0]` return `articles` which is correct.
![2022-10-04_15-29](https://user-images.githubusercontent.com/2996543/193772220-649d1c5a-6200-4c46-b657-757a4b1c063b.png)

**Comment by phuongnq** [comment]
In Crafter v4, I got the following error: 
![2022-10-04_15-05](https://user-images.githubusercontent.com/2996543/193774293-547c4001-9c5d-483b-9d46-32d41c5ccf42.png)

**Comment by rart** [comment]
@russdanner @sumerjabri what is the expectation with this particular macro in embedded components?

**Comment by russdanner** [comment]
We looked at the code that processes the macro:
Note that the parent path is always derived from the url
https://github.com/craftercms/studio-ui/blob/support/3.1.x/static-assets/components/cstudio-common/common-api.js#L3270

When an item embedded object sub form is opened from the node selector the URL takes the following shape:
`http://localhost:8080/studio/form?site=parentmacro&form=/component/left-rail&path=62a9d0e6-6440-12db-60e5-0fc5fce74a83&isInclude=true&iceComponent=true&edit=true&editorId=c2690f96-f250-468c-7e3d-d54463bfc39c`

Note that path is an object ID.

The issue is that `parentPath` parameter should be sent with the value of the content file above.

Meaning that if 
A is an article and has a reference to B which is an embedded content object parentPath should = the path to A

If A has shared child content B and B has a reference to an embedded component C then the parentPath should be to B

**Comment by phuongnq** [comment]
verified.
