### ISSUE TITLE
[studio] The `/search/search.json` API 2 is returning HTTP 500 on requests with empty keywords, single chars or spaces between chars

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5812]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

The `/search/search.json` API 2 is returning HTTP 500 on requests with empty keywords, single chars or spaces between chars. For example, sending a keyword `h i`, `a` will return a Internal System Failure. 

### Steps to reproduce

Steps:

1. Go to any project of your choice.
2. Click on `Search`
3. See the issue.

### Relevant log output

```shell
[ERROR] 2022-10-05T15:29:39,450 [http-nio-8080-exec-8] [v2.ExceptionHandlers] | API endpoint 'http://localhost:8080/studio/api/2/search/search.json?siteId=test-site' failed with response 'ApiResponse{code=1000, message='Internal system failure: Error executing search in Elasticsearch', remedialAction='Contact support', documentationUrl=''}' 
org.craftercms.studio.api.v1.exception.ServiceLayerException: Error executing search in Elasticsearch
```

### Screenshots and/or videos

![Screenshot from 2022-10-04 14-26-48](https://user-images.githubusercontent.com/90878288/194167723-1594d5a4-607e-4801-8b5a-a30dbe2f9985.png)

**Comment by Euquimides** [comment]
@sumerjabri and @phuongnq, I am noticing that adding single `"` quote, will return 500, but not when enclosing the search in quotes, like for example  "castle". Also `{` or `[` will return 500. In this last case, shouldn't the response be 400?

**Comment by phuongnq** [comment]
@sumerjabri This happens because of the regex search for `localId` (a path) here: https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/search/internal/SearchServiceInternalImpl.java#L545
If we have any [reserved character](https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html#regexp-reserved-characters) without a proper format, it could fail with malformat. For example: a `[` without a `]`.
Assuming the input keyword itself is not a regex (We don't support regex in the search form), searching with any special characters in the path field won't make any sense and should return 0 hits for this part. We are using `should` (OR logic) so 0 hits in this part won't affect other search multi match queries.
I created a PR to check the keyword:

* If it is a part of a proper path (support with any alphanumeric, `/`, `.`, `-`, `_` characters), then we can search with the regex. 
* If it contains any other characters, do not add this `localId` search. Note that this won't affect the requirement to support searching with double quote (`"<keyword>"`) as it has been [included](https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/search/internal/SearchServiceInternalImpl.java#L501) and [replaced](https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/search/internal/SearchServiceInternalImpl.java#L514).

**Comment by Euquimides** [comment]
Hi! Updated and rechecked the issue. Validated for Crafter v4. Thank you! Closing this ticket.
