### ISSUE TITLE
[studio] Dashboard UI performance with several hundred unpublished items

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5813]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

 When opening the dashboard in Studio, having so many unpublished items will cause the dashboard to take a long time to populate, and selecting individual items also takes time.

### Steps to reproduce

Steps:

1. Create a new site
2. Populate several hundred assets. Ex, use the following bash command and then commit to sandbox:

```
for i in {1..200}; do touch sample_file${i}; done
```
3. Open the Dashboard, and click "Show Unpublished"
4. Notice that the dashboard takes time to display and the checkbox sometimes does not responsive or takes time

Updates are needed for current blueprints:

- [ ] UM
- [x] Existing blueprints

`craftercms.components.AwaitingApprovalDashlet` needs to be replaced with 
`craftercms.components.LegacyInReviewDashlet` and `craftercms.components.LegacyUnpublishedDashlet`

### Screenshots and/or videos

![2022-10-07_10-07](https://user-images.githubusercontent.com/2996543/194459835-25db1dd5-66f8-4d13-baf7-59816ea6ad7b.png)
![2022-10-07_10-09_1](https://user-images.githubusercontent.com/2996543/194459845-cf4dd859-3ec6-4050-ac9c-1dd72abf3dcf.png)

**Comment by sumerjabri** [comment]
Use this API to list items awaiting approval:
`/dashboard/content/pending_approval`
https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/dashboard/getDashboardContentPendingApproval

Use this API to list unpublished items:
`/dashboard/content/unpublished`
https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/dashboard/getDashboardContentUnpublished

These will replace:
`get-go-live-items.json` which is used in both cases.

Split the old dashboard "Items Waiting for Approval" into two Dashboards:
- "In Review" -- Use the API "pending_approval"
- "Unpublished" -- Use the API "unpublished"
  - Add a button at the top of this called "Publish All" which uses the API https://app.swaggerhub.com/apis/craftercms/studio/4.0.2.0#/publishing/publishAll just like the `Publish All` function in the publishing tools which then pops up a dialog similar to this:
![image](https://user-images.githubusercontent.com/3931908/211622643-132e143f-5d16-4a51-82b6-e8367e5e14af.png)

Remember:
- The new APIs **_will not_** classify the returned items into Pages/Components/Assets/etc.
- The new APIs paginate, so for now since we're using the old UI, just use "Show 10" (10, 20, 50, All ... like the other dashboards but includes "All" where all sets the pagination to very large)
- The new APIs return Sandbox items

**Comment by jvega190** [comment]
@sumerjabri assigning it to you for the UM work (ticket already updated). I'll start working on existing bps.

**Comment by phuongnq** [comment]
verified
