### ISSUE TITLE
[studio][studio-ui] The button `...1 more item` in the sidebar is calling `/content/children_by_path` with offset +10 for each call

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#5853]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you duplicate an item either on `Templates` or `Scripts`, a button named `...1 more item` in the sidebar will appear. Upon clicking it, it will call `/content/children_by_path` but it will keep adding 10 to the `offset` parameter of the request with each click. 

### Steps to reproduce

Steps:

1. Create a new site, preferably Editorial BP.
2. Duplicate an item in a directory of either `Scripts` or `Templates`, For example, duplicate an item in `Scripts` -> `rest`. If the button `..1 more item` doesn't appear, change directory in the same section and duplicate. 
3. Once the button has appeared, click on it. 
4. See the issue. 

### Relevant log output

```shell
{"response":{"code":0,"message":"OK","remedialAction":"","documentationUrl":""},"total":3,"offset":20,"limit":10,"levelDescriptor":null,"children":null}
```

### Screenshots and/or videos

https://user-images.githubusercontent.com/90878288/200082866-f03c47ab-d038-451c-8b22-694519d348a5.mp4

**Comment by jvega190** [comment]
@sumerjabri @jmendeza there's a problem in the `studio/api/2/content/children_by_path` API, where sometimes when duplicating it returns the correct total of items, but it doesn't include the new duplicated item in the list

![Screenshot from 2022-12-08 10-13-43](https://user-images.githubusercontent.com/18267471/206501207-823bd0f9-3fe5-4caf-9f26-02273cee047a.png).

That causes the UI to show the '1 more item' button.

**Comment by phuongnq** [comment]
This happens because we call the API `studio/api/2/content/children_by_path` before the duplication operation responds. See the below screenshot:

![2023-02-06_11-03](https://user-images.githubusercontent.com/2996543/216902007-5416a94b-ca8c-4db6-8ddf-3449c990021f.png)

In the screenshot,  seem like we call the duplication API `/studio/api/2/content/duplicate` and `studio/api/2/content/children_by_path` in parallel. As a result, there are chances that we call to get the children of the folder before the duplication (insert a new item to DB) is performed. The case that the total number was correct but the items were not is a result of the following queries order:

```
query to get children by path => inserts new duplicated item => query to get total children by a path.
```

I sent a PR for the backend to fix the mismatch by counting the total first and then querying children's items. 

But it could send back to the UI the old number of items since the duplication has not been completed yet. 

@rart @jvega190 Any chance we can improve the order of API calls that only call the `studio/api/2/content/children_by_path` after the duplication has been completed?

**Comment by sumerjabri** [comment]
@phuongnq please see if this can be corrected by changing the order of events sent via the socket to the UI.
