### ISSUE TITLE
[mariadb4j] Update to latest

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5929]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Our fork of MariaDB4j is lagging behind, it needs to be updated.

### Describe the solution you'd like

Update our fork of MariaDB4j to the latest (while keeping the DB version on the same major/minor).

**Comment by sumerjabri** [comment]
Related to: https://github.com/craftercms/craftercms/issues/5454

**Comment by phuongnq** [comment]
@sumerjabri The PR is ready for review. I update to a new version `2.6.0`.

Note that the `testLocalMariaDB` test case is commented out since this requires setting up MariaDB locally. (https://github.com/craftercms/MariaDB4j/pull/137/files#diff-0694870a2a95f83bf1416f4454828bec13dac6ff7772d5326832f2409f63661c)

You can also review the release note here: https://github.com/vorburger/MariaDB4j/releases/tag/mariaDB4j-2.6.0

**Comment by sumerjabri** [comment]
Reminder to update our projects to use 2.6.0
