### ISSUE TITLE
[studio] New dashboard APIs updates

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#5970]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Some API updates are needed for the new dashboards since we'll be using items instead of packages.

- Activity (`dashboard/activity`): Please return items instead of packages (right now it's returning items for single-item activities only).

- Schedule for publish (`/dashboard/publishing/scheduled`): API doesn't return any packages, also, it should return items instead of packages

- Recently published (`/dashboard/publishing/history`): API doesn't return any packages, also, it should return items instead of packages

### Describe the solution you'd like

Dashboard APIs should all return items instead of packages

**Comment by phuongnq** [comment]
Hi @sumerjabri @jvega190  I have some confirmation regarding the dashboard APIs.

> 1. Activity (dashboard/activity): Please return items instead of packages (right now it's returning items for single-item activities only).

We get the activity from the `activity_stream` table. This table has mixed records for both activities by `path` for single-item and activities for packages.

An example of an activity for a package is when you commit some files via Git and then choose publishing by commit id. In this case, there is only one record in the `activity_stream` table. See the below screenshot:

![activity_stream](https://user-images.githubusercontent.com/2996543/223692712-71edcfa4-f6be-4a9b-8e2b-3e6893206a0c.png)

But there are 2 items in the package:

![activity_package_db](https://user-images.githubusercontent.com/2996543/223693232-fbcaa841-d898-4dde-b3a5-592e34e148be.png)

For this activity, this API is returning the package id instead of the package items:

![activity_package](https://user-images.githubusercontent.com/2996543/223693875-8c65d083-b21d-4191-b975-3c4ed4a022cb.png)

=> What is the expected response for this case? Do we still want to have this activity as a single activity and inside it, return the item's details (Still counting as one activity)? And more detail, do we want `SandboxItem` or `DetailedItem`? 

> 2. Schedule for publish (/dashboard/publishing/scheduled): API doesn't return any packages, also, it should return items instead of packages

I will update to send `DetailedItem` for this API, similar to what we have done for Pending approval items in https://github.com/craftercms/craftercms/issues/5901

=> One question regarding the API parameters, I noticed that we have `dateFrom` and `dateTo` to filter the result. Do we really need this? I'm asking because if filtering by date is not required, we only have to query the `item` table relying on the `state` bit. But if we also want filtering by date, we need to join other tables such as `workflow` or `publish_request`, and in the UI, seems like we don't use these parameters.

> 3. Recently published (/dashboard/publishing/history): API doesn't return any packages, also, it should return items instead of packages

To be correct, we currently return packages, and it is from the `publish_request` table.
![2023-03-08_18-15](https://user-images.githubusercontent.com/2996543/223699408-7d5d3c23-b6bc-4dd7-ab89-dce88e0dc921.png)

If we want to return items for this case, what is the correct count if we publish the same items multiple times? 
Will we count the same path as 2 separate histories and return both?

**Comment by sumerjabri** [comment]
I'll take this ticket to better define what's needed.

**Comment by sumerjabri** [comment]
This is no longer needed. Will open a new ticket for any new issues.
