### ISSUE TITLE
Test out MariaDB4j v3

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6040]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We're on MariaDB4j 2

### Describe the solution you'd like

See if we can:
- Upgrade to MariaDB4j v3
- ~~Use that out of the box without our extensions to it~~

**Comment by phuongnq** [comment]
@sumerjabri 
* We cannot upgrade MariaDB4j v3 this time since it has a dependency on Spring Framework and Spring Boot 6. We can upgrade this along with the Spring upgrade.
* We cannot use that out of the box without our extensions to it because: 
  * There is no option to set the root password out of the box in v3 
  * The DB version is behind our current (out of the box: 10.2.11, we are using 10.4.20)
  * We also modified some log level

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/5977
