### ISSUE TITLE
[studio] Improve Upgrade Manager's startup time when many sites exist

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6075]
### Latest version

- [x] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Today the upgrade manager processes a list of files for each site. When there are many sites, this process can take a long time.

### Describe the solution you'd like

There are several possible solutions.

1. The Upgrade Manager (UM) should work from a manifest-style file rather than check each file individually.
2. Support disabling the UM

**Comment by sumerjabri** [comment]
Design Approach:
1. Maintain a single manifest file in `/config`, the file has a structure similar to (let's finalize the structure during a design session):
```
<config-manifest>
    <module name="studio">
      <config-file>
        <path>filepath and name</path>
        <version>current file version</version>
      </config-file>
    </module>
</config-manifest>
```
2. Remove the version numbers from individual files
3. UM will read the manifest and act based on that

The above approach means a single read per site will give UM the info it needs.

Let's review.

**Comment by sumerjabri** [comment]
Fix in 4.1 only, please.

**Comment by jmendeza** [comment]
As discussed, instead of creating a manifest file holding the versions, we are changing the approach to read the version using pattern matching `<version></version>`

**Comment by jmendeza** [comment]
In order to boost a little startup time:
- Updated tomcat configs to add a list of jars to be ignored when scanning for TLDs on startup
- Updated version provider so it stops reading XML files once `<version>` has been found

Local tests even with many sites (60) the UM time only accounts for a small fraction (6-8s) of total startup time (~35s)

It would be helpful to see the logs of an install presenting issues, so the timestamps can give us some hints on the actual causes of the issue.
cc: @sumerjabri @russdanner

**Comment by russdanner** [comment]
Confirmed
