### ISSUE TITLE
[search] Make document parser fields configurable

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#6215]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

`AbstractDocumentParser` uses a set of fields to parse a static document into: https://github.com/craftercms/search/blob/develop/crafter-search-opensearch/src/main/java/org/craftercms/search/opensearch/impl/AbstractDocumentParser.java#L27:

```
    private static final String DEFAULT_FIELD_NAME_CONTENT = "content";
    private static final String DEFAULT_FIELD_NAME_AUTHOR = "author";
    private static final String DEFAULT_FIELD_NAME_TITLE = "title";
    private static final String DEFAULT_FIELD_NAME_KEYWORDS = "keywords";
    private static final String DEFAULT_FIELD_NAME_DESCRIPTION = "description";
    private static final String DEFAULT_FIELD_NAME_CONTENT_TYPE = "content-type";
    private static final String DEFAULT_FIELD_NAME_CREATED = "created";
    private static final String DEFAULT_FIELD_NAME_MODIFIED = "modified";
```

This may cause conflict of the mapping if some developers use a custom mapping for open search. For example, if we define `content` as an object instead of a string, this field will conflict with the Abstract Document Parser hard coded `content` field name.

### Describe the solution you'd like

Make the `AbstractDocumentParser` or `TikaDocumentParser` fields definition configurable

**Comment by russdanner** [comment]
The context or reason for this update would be to rename a reserved word in CrafterCMS's model which is used as a contract between components. This should not be allowed as part of the platform as it can cause downstream integration issues between the components.

**Comment by russdanner** [comment]
The correct solution in the event of a conflict is to update the content model and content with a new name.

1. Use a script to update content types and content instances with the new names.
2. With respect to publishing and workflow state (if maintaining these is a requirement)
2a. Dump/copy the item state table before the migration and re-apply the states after the migration commit is processed to keep the states in the condition they were in prior to the migration. 
2b. To make sure the exact version that is published, remains published: Run the content migration script in both/all sandbox and published repo branches (rather than publishing all.)
2c. This will cause the published content to be re-indexed. If the content volume is large, then re-index offline and copy the new index in during the go-live operation.
