### ISSUE TITLE
[studio][studio-ui] Static Assets flattens nested folders on bulk upload

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#6430]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

4.0.x static assets bulk upload used to support bulk uploading nested folders. The system would create folder structure when dragged onto the upload dialog and nest files and folders inside.

In 4.1.2, 4.1.3+ files in nested folders are flattened into the top level folder.

### Steps to reproduce

Steps:

1. In the Editorial blueprint: right-click on static-assets/images and choose upload.
2. Drag a folder that contains nested folders and assets into the dialog.
3. Note that the nested files end up in the /static-assets/images, and no nested structure is created.

**Comment by sumerjabri** [comment]
@rart, we must also see if this affects 4.0.x

**Comment by rart** [comment]
@jvega190 

It appears uppy might have changed this behaviour. Review uppy Dashboard differences between the latest and the last confirmed version with folders handled as expected.

Start with 4.0.x and work your way backward to identify our latest release with the expected behaviour and use that uppy version as reference.

Check uppy's change and release logs to identify if it can be somehow configured or if they make mention of something related to this in logs or issues.

**Comment by Euquimides** [comment]
Hi @jvega190 ! While validating this ticket, I noticed that if picking the option `Browse Folders` instead of drag n' drop the nested folder, will flatten the bulk upload. In the case of `drag n' drop` for bulk upload, the flattening of nested folders is no happening. Can you please check this out? Thanks!

**Comment by Euquimides** [comment]
Hi! Updated and rechecked. Fix verified for v4.1.x. Will wait for the rest of the versions to be updated. Thank you!

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for v4.0.8, v4.1.3 and v4.2.0. Thank you! Closing this ticket.
