### ISSUE TITLE
Component Data Source - option to disable create + macros for paths

### ISSUE THREAD

**Issue by tfield** [craftercms/craftercms#6652]
### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

When creating new content using the component datasource, we want to be able to control where the new content is created, beyond the base repository path. Sometimes we want to disable searching altogether.

### Describe the solution you'd like

- enable macros on all configurable paths
- rename "Base Repository Path" to "Path for New Items" or similar - Base Repository Path is confusing.
- add "Enable Create" checkbox
- ensure that the "Add" button for included items looks good when many datasources are configured on the same field (because we will end up using one datasource per content type)

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/6649

**Comment by rart** [comment]
@jvega190 please make the macros work on the browse path too.

**Comment by Euquimides** [comment]
Hi @rart and @jvega190 ! Since there has been changes to the components data source, blueprints must be update to reflect them. For example, notice that in 3.1.x there is an option for browsing for "Feature" components, but not in 4.1.x and 4.2 in Editorial BP. 

![Screenshot from 2024-04-04 16-02-21](https://github.com/craftercms/craftercms/assets/90878288/c1dea2dd-d03a-4209-95bc-308d9f228bb5)
![Screenshot from 2024-04-04 15-38-45](https://github.com/craftercms/craftercms/assets/90878288/9b90afc1-8a72-4c97-abcd-999b8112e655)

Could you please take a look at this? Thanks!

**Comment by Euquimides** [comment]
Hi! Feature implementation verified for both v4.1.x and 4.2.0. Thank you! Closing this ticket.
