### ISSUE TITLE
Grab fails in REST Script

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7170]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Using @grabs in REST scripts causes script compilation failures.

### Steps to reproduce

Steps:

1. Configure and execute the following REST script and see error
```
@Grab(group='com.squareup.okhttp3', module='okhttp', version='4.12.0', initClass=false)

return "hello"
```

### Relevant log output

```
[ERROR] 2024-08-15T12:59:20,051 [http-nio-8080-exec-4] [ai-playground] [rest.RestScriptsController] | Error executing REST script at '/scripts/rest/slides.get.groovy' 
org.craftercms.engine.exception.ScriptException: startup failed:
site:/scripts/rest/slides.get.groovy: 4: Unexpected input: '@Grab(group='com.squareup.okhttp3', module='okhttp', version='4.12.0', initClass=false)\n\n\nreturn' @ line 4, column 1.
   return "hello"
```

**Comment by phuongnq** [comment]
@russdanner @sumerjabri The error is the expected behavior for Groovy. You will see the same error when running a Groovy script locally. Grab can only be applied as an annotation to certain targets.
From their doc: https://docs.groovy-lang.org/latest/html/documentation/grape.html#Grape-Annotation
> This will have the effect of adding the library to the classloader of the groovy compiler. This annotation is detected and evaluated before any other resolution of classes in the script, so imported classes can be properly resolved by a @Grab annotation.

So if we have a class, method, or import, the annotation `@Grab` works as expected:

// this works
```
@Grab(group='com.squareup.okhttp3', module='okhttp', version='4.12.0', initClass=false)
class Test {}
return "hello"
```

// this works
```
@Grab(group='com.squareup.okhttp3', module='okhttp', version='4.12.0', initClass=false)
def test() {}
return "hello"
```

// this works (From Editorial BP to import a class)
```
@Grab(group='com.squareup.okhttp3', module='okhttp', version='4.12.0', initClass=false)
import  org.craftercms.sites.editorial.ProfileUtils
return "hello"
```

If we would like to run this directly in the script execution block, we can use the static method `Grape.grab`:
// this works
```
import groovy.grape.Grape
Grape.grab(group: 'com.squareup.okhttp3', module: 'okhttp', version: '4.12.0', initClass: false)
return "hello"
```
