### ISSUE TITLE
Item options dialog box prohibits the ability to open another item's dialog box

### ISSUE THREAD

**Issue by AndyReiter** [craftercms/craftercms#7481]
### CI Number

5401

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

In the sidebar, after right-clicking on a page to select Edit, the browser menu shows up if you right-click on another page instead until you left-click somewhere to hide the current pop-up. If someone right-clicks on the wrong page, it’s a few extra clicks.

See video: https://www.loom.com/share/d3a02d5111c84312b4f60bd53e91f1b4?sid=9115be82-8f1a-43e5-94e1-79d541113b14

### Describe the solution you'd like

Add the ability to open a different item's options dialogue while you have an options dialogue box open.

**Comment by rart** [comment]
The item menu is essentially a modal dialog so the rest of the UI is disabled putting the focus on the item menu. This is supports **keyboard navigation** and **accessibility**.

Please teach and advice users to use the escape key and/or the backdrop click. Hitting escape will close the menu. Clicking anywhere outside the menu paper will also close it.

Suggest using the menu button instead of right click could also decrease the likelihood of opening the wrong item menu.

@russdanner @AndyReiter

**Comment by sumerjabri** [comment]
We're using a different UI framework that doesn't support the old mechanics.
