### ISSUE TITLE
CrafterCMS Studio log out throws an access denied page

### ISSUE THREAD

**Issue by Euquimides** [craftercms/craftercms#7551]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.2.x
- [ ] The issue is in the latest released 4.1.x

### Describe the issue

When log out from Studio, an access denied page appears.

### Steps to reproduce

Steps:

1. Startup CrafterCMS Studio.
2. Log in to Studio.
3. Then log out from Studio.
4. See the issue: an access denied page appears

### Screenshots and/or videos

![image](https://github.com/user-attachments/assets/9f295e04-ef84-477f-b2be-51cb241fb962)

**Comment by jmendeza** [comment]
This works with tomcat 10, not with tomcat 11. 
Also, web sockets are failing to connect:
![image](https://github.com/user-attachments/assets/f7bdd721-909b-478e-9a37-98b1ac81d82d)


Notice xsrf token is undefined ^

**Comment by phuongnq** [comment]
@sumerjabri @jmendeza The issue with logout occurs because the XSRF-TOKEN is `undefined`, as Jonathan pointed out. This happens because the UI (JavaScript) retrieves the token from cookies, but in Tomcat 11, the cookie is marked with the HttpOnly and Secure flags even when these flags should not be set. Which causes the token to be `undefined`.

From the changelog https://tomcat.apache.org/tomcat-11.0-doc/changelog.html:

> Refactor the internal representation of the HttpOnly and Secure attributes to use the empty string as the value for consistency with the recent changes to Set-Cookie header generation.

In this context, Spring Security sets these flags with a false value, which worked in Tomcat 10. However, in Tomcat 11, these flags should not be set at all. Even an empty value results in the flags being applied, as they are treated as boolean flags.

To address this, we have a few options:

1. Wait for Spring Security to fix the issue.
2. Implement a custom CsrfTokenRepository to set the HttpOnly and Secure flags only when the value is explicitly true.
3. Change how the UI retrieves the token, avoiding reliance on the cookie.

I’ve submitted a PR that implements option (2). If we decide to go this route, we can review the customization and remove it once Spring Security resolves the problem.

**Comment by Euquimides** [comment]
Hi! Updated and rechecked this issue. Fix verified for v5.0.0. Thank you! Closing this ticket.
